// This file reads the data from the items.json file and converts it into a JavaScript object

const itemsData = {
    "weapons": [
        {
            "offenseFireMin": 3,
            "name": "Bow of the Hegelob",
            "effects": [],
            "tags": ["L54", "constant"],
            "offenseWaterMin": 3,
            "offenseFireMax": 3,
            "offenseEarthMax": 3,
            "offenseEarthMin": 3,
            "offenseWaterMax": 3,
            "id": "Bow of the Hegelob",
            "icon": "https://images.neopets.com/items/shw_hegelob_bow.gif"
        },
        {
            "offenseFireMin": 3,
            "name": "Carved Qasalan Blowgun",
            "effects": [],
            "offenseLightMin": 3,
            "offenseFireMax": 3,
            "offenseEarthMax": 3,
            "offenseEarthMin": 3,
            "id": "Carved Qasalan Blowgun",
            "icon": "https://images.neopets.com/items/bd_qs_blowgun.gif",
            "tags": ["L54", "constant"]
        },
        {
            "offenseFireMin": 3,
            "name": "Chia Ray Gun (Chia)",
            "effects": [],
            "offenseLightMin": 5,
            "offenseFireMax": 3,
            "offenseLightMax": 5,
            "id": "Chia Ray Gun (Chia)",
            "icon": "https://images.neopets.com/items/bd_chia_raygun.gif",
            "tags": ["L54", "constant", "chia"]
        },
        {
            "name": "Cooty Crossbow",
            "offenseDarkMax": 3,
            "effects": [],
            "offenseWaterMin": 3,
            "offenseDarkMin": 3,
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "offenseWaterMax": 3,
            "id": "Cooty Crossbow",
            "icon": "https://images.neopets.com/items/wea_ddy21_cootycrossbow.gif",
            "tags": ["L54", "constant"]
        },
        {
            "icon": "https://images.neopets.com/items/bd_ddy18_dangerdodgeball.gif",
            "name": "Dangerous Dodgeball",
            "offenseDarkMax": 7,
            "effects": [],
            "offenseDarkMin": 7,
            "id": "Dangerous Dodgeball",
            "tags": ["L54", "constant"]
        },
        {
            "icon": "https://images.neopets.com/items/bd_darkduck.gif",
            "name": "Dark Battle Duck",
            "offenseDarkMax": 3,
            "effects": [],
            "offenseWaterMin": 5,
            "offenseDarkMin": 3,
            "offenseWaterMax": 5,
            "id": "Dark Battle Duck",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Decorative Maractite Sword",
            "offensePhysicalMin": 3,
            "effects": [],
            "offenseWaterMin": 5,
            "offensePhysicalMax": 3,
            "offenseWaterMax": 5,
            "id": "Decorative Maractite Sword",
            "icon": "https://images.neopets.com/items/bd_maractite_sword.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Desert Crossbow",
            "offenseFireMin": 6,
            "effects": [],
            "offenseLightMin": 2,
            "offenseFireMax": 6,
            "offenseLightMax": 2,
            "id": "Desert Crossbow",
            "icon": "https://images.neopets.com/items/wea_tge_dcrossbow.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Dual Batons of Katsuo",
            "offenseFireMin": 2,
            "offensePhysicalMin": 2,
            "offenseDarkMax": 2,
            "effects": [],
            "offensePhysicalMax": 2,
            "offenseDarkMin": 2,
            "offenseFireMax": 2,
            "offenseEarthMax": 3,
            "offenseEarthMin": 3,
            "id": "Dual Batons of Katsuo",
            "icon": "https://images.neopets.com/items/wea_dual_batons.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Essence of Esophagor",
            "effects": [],
            "offenseWaterMin": 4.5,
            "offenseEarthMax": 4.5,
            "offenseEarthMin": 4.5,
            "offenseWaterMax": 4.5,
            "id": "Essence of Esophagor",
            "icon": "https://images.neopets.com/items/bd_esoph_essence.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Exceptionally Tiny Laser Cannon",
            "offensePhysicalMin": 0,
            "effects": [],
            "offenseWaterMin": 2,
            "offenseLightMin": 3,
            "offenseEarthMax": 3,
            "offenseEarthMin": 3,
            "offenseWaterMax": 2,
            "offenseLightMax": 3,
            "id": "Exceptionally Tiny Laser Cannon",
            "icon": "https://images.neopets.com/items/ros_bd_tinylaser.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Festive Cutlass",
            "offenseFireMin": 5,
            "offenseDarkMax": 3,
            "effects": [],
            "offenseDarkMin": 3,
            "offenseFireMax": 5,
            "id": "Festive Cutlass",
            "icon": "https://images.neopets.com/items/festive_cutlass.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Ice Club",
            "offensePhysicalMin": 3,
            "effects": [],
            "offenseWaterMin": 3,
            "offensePhysicalMax": 3,
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "offenseWaterMax": 3,
            "id": "Ice Club",
            "icon": "https://images.neopets.com/items/bd_ice_cube_club.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Kazeriu Whip",
            "offensePhysicalMin": 3,
            "effects": [],
            "offensePhysicalMax": 3,
            "offenseAirMax": 5,
            "offenseAirMin": 5,
            "id": "Kazeriu Whip",
            "icon": "https://images.neopets.com/items/shw_whip_kazeriu.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Korbat Power Blaster",
            "effects": [],
            "offenseWaterMin": 3,
            "offenseAirMax": 5,
            "offenseAirMin": 5,
            "offenseWaterMax": 3,
            "id": "Korbat Power Blaster",
            "icon": "https://images.neopets.com/items/bd_korblaster.gif",
            "tags": ["L54", "constant", "korbat"]
        },
        {
            "name": "Lavaball",
            "offenseFireMin": 6,
            "effects": [],
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "offenseFireMax": 6,
            "id": "Lavaball",
            "icon": "https://images.neopets.com/items/toy_lavaball.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Lutari Lance (Lutari)",
            "offensePhysicalMin": 3,
            "effects": [],
            "offensePhysicalMax": 3,
            "offenseAirMax": 2.66,
            "offenseAirMin": 2.66,
            "offenseEarthMax": 3,
            "offenseEarthMin": 3,
            "id": "Lutari Lance (Lutari)",
            "icon": "https://images.neopets.com/items/bd_lutari_lance.gif",
            "tags": ["L54", "constant", "lutari"]
        },
        {
            "name": "Merciless Idiom",
            "offenseDarkMax": 3,
            "effects": [],
            "offenseDarkMin": 3,
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "offenseLightMin": 3,
            "offenseLightMax": 3,
            "id": "Merciless Idiom",
            "icon": "https://images.neopets.com/items/wea_thruster.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Night Katana",
            "offensePhysicalMin": 3,
            "offenseDarkMax": 3,
            "effects": [],
            "offensePhysicalMax": 3,
            "offenseDarkMin": 3,
            "offenseAirMax": 2,
            "offenseAirMin": 2,
            "id": "Night Katana",
            "icon": "https://images.neopets.com/items/bd_blue_katana.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Pickle Spear",
            "effects": [],
            "offenseEarthMax": 8,
            "offenseEarthMin": 8,
            "id": "Pickle Spear",
            "icon": "https://images.neopets.com/items/bd_pickle_spear.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Pike Pike",
            "effects": [],
            "offenseWaterMin": 4.5,
            "offenseLightMin": 4.5,
            "offenseWaterMax": 4.5,
            "offenseLightMax": 4.5,
            "id": "Pike Pike",
            "icon": "https://images.neopets.com/items/bd_pike_pike.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Psellias Fighting Fan",
            "offensePhysicalMin": 3,
            "effects": [],
            "offensePhysicalMax": 3,
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "offenseLightMin": 3,
            "offenseLightMax": 3,
            "id": "Psellias Fighting Fan",
            "icon": "https://images.neopets.com/items/bd_airfaerie_purplefan.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Rainbow Scroll",
            "effects": [],
            "offenseWaterMin": 3,
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "offenseLightMin": 3,
            "offenseWaterMax": 3,
            "offenseLightMax": 3,
            "id": "Rainbow Scroll",
            "icon": "https://images.neopets.com/items/bvs_rainbow_scroll.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Ridiculously Heavy Battle Hammer",
            "offensePhysicalMin": 3,
            "effects": [],
            "offensePhysicalMax": 3,
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "offenseEarthMax": 3,
            "offenseEarthMin": 3,
            "id": "Ridiculously Heavy Battle Hammer",
            "icon": "https://images.neopets.com/items/bd_heavybattlehammer.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Rusty Cleaver",
            "offenseFireMin": 6,
            "offensePhysicalMin": 3,
            "effects": [],
            "offensePhysicalMax": 3,
            "offenseFireMax": 6,
            "id": "Rusty Cleaver",
            "icon": "https://images.neopets.com/items/bd_hw_cleaver_rusty.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Scroll of Forgotten Promises",
            "offenseDarkMax": 3,
            "effects": [],
            "offenseDarkMin": 3,
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "offenseEarthMax": 2,
            "offenseEarthMin": 2,
            "id": "Scroll of Forgotten Promises",
            "icon": "https://images.neopets.com/items/bvs_scroll_forgottenpromises.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Scroll of the Battlefield",
            "offensePhysicalMin": 6,
            "effects": [],
            "offensePhysicalMax": 6,
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "id": "Scroll of the Battlefield",
            "icon": "https://images.neopets.com/items/bvs_thebattlefield.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Scroll of the Earth",
            "effects": [],
            "offenseWaterMin": 2.6,
            "offenseEarthMax": 6,
            "offenseWaterMax": 2.6,
            "id": "Scroll of the Earth",
            "icon": "https://images.neopets.com/items/bvs_earth_scroll.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Shuko",
            "effects": [],
            "offenseWaterMin": 7,
            "offenseWaterMax": 7,
            "id": "Shuko",
            "icon": "https://images.neopets.com/items/shw_shuko.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Silver Draik Bow (Draik)",
            "offenseFireMin": 3,
            "offensePhysicalMin": 3,
            "effects": [],
            "offensePhysicalMax": 3,
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "offenseFireMax": 3,
            "id": "Silver Draik Bow (Draik)",
            "icon": "https://images.neopets.com/items/bd_draik_bow.gif",
            "tags": ["L54", "constant", "draik"]
        },
        {
            "name": "Skeletal Fire Gun",
            "offenseFireMin": 6,
            "effects": [],
            "offenseLightMin": 2,
            "offenseFireMax": 6,
            "offenseLightMax": 2,
            "id": "Skeletal Fire Gun",
            "icon": "https://images.neopets.com/items/bd_haunted_firegun.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Spearmint",
            "effects": [],
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "offenseEarthMax": 5,
            "offenseEarthMin": 5,
            "id": "Spearmint",
            "icon": "https://images.neopets.com/items/bd_spearmint.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Stone Club",
            "offensePhysicalMin": 3,
            "effects": [],
            "offensePhysicalMax": 3,
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "offenseEarthMax": 3,
            "offenseEarthMin": 3,
            "id": "Stone Club",
            "icon": "https://images.neopets.com/items/bd_tyr_club.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Strange Marking Stone Necklace",
            "effects": [],
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "offenseLightMin": 3,
            "offenseEarthMax": 3,
            "offenseEarthMin": 3,
            "offenseLightMax": 3,
            "id": "Strange Marking Stone Necklace",
            "icon": "https://images.neopets.com/items/bd_necklace_strangestone.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Throwing Cutlass",
            "effects": [],
            "offenseWaterMin": 3,
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "offenseEarthMax": 3,
            "offenseEarthMin": 3,
            "offenseWaterMax": 3,
            "id": "Throwing Cutlass",
            "icon": "https://images.neopets.com/items/bd_gmc_cutlass_throwing.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Tuskaninny Battle Trumpet",
            "effects": [],
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "offenseEarthMax": 5,
            "offenseEarthMin": 5,
            "id": "Tuskaninny Battle Trumpet",
            "icon": "https://images.neopets.com/items/bd_tusk_straw.gif",
            "tags": ["L54", "constant", "tuskaninny"]
        },
        {
            "name": "Water Bazooka",
            "offensePhysicalMin": 4,
            "effects": [],
            "offensePhysicalMax": 4,
            "offenseWaterMin": 4,
            "offenseWaterMax": 4,
            "id": "Water Bazooka",
            "icon": "https://images.neopets.com/items/bd_ddy18_waterbazooka.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Sword of Elements",
            "offenseFireMin": 2,
            "offenseDarkMax": 2,
            "effects": [],
            "offenseDarkMin": 2,
            "offenseAirMax": 2,
            "offenseAirMin": 2,
            "offenseLightMin": 2,
            "offenseFireMax": 2,
            "offenseLightMax": 2,
            "id": "Sword of Elements",
            "icon": "https://images.neopets.com/items/bd_gmc2013_rainswrd.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Pumpkin Stick",
            "effects": [],
            "offenseLightMin": 8,
            "offenseLightMax": 8,
            "id": "Pumpkin Stick",
            "icon": "https://images.neopets.com/items/bd_pumpkin_stick.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Altadorian Swordbreaker",
            "effects": [
                "Blocks 100% of physical"
            ],
            "offenseEarthMax": 5,
            "offenseEarthMin": 5,
            "id": "Altadorian Swordbreaker",
            "percentagePhysicalBlocked": 100,
            "icon": "https://images.neopets.com/items/ala_sword_altadbreak.gif",
            "tags": ["L54", "blocker", "multi-duty"]
        },
        {
            "name": "Amulet of Altador",
            "defenseWaterMin": 3,
            "defenseWaterMax": 3,
            "defenseDarkMax": 3,
            "effects": [],
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "offenseLightMin": 3,
            "defenseDarkMin": 3,
            "offenseLightMax": 3,
            "defensePhysicalMin": 3,
            "id": "Amulet of Altador",
            "icon": "https://images.neopets.com/items/bd_amulet_of_altador.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Amulet of Inevitable Betrayal",
            "defenseLightMax": 3,
            "offenseDarkMax": 2,
            "effects": [],
            "offenseWaterMin": 3,
            "offenseDarkMin": 2,
            "offenseAirMax": 2,
            "offenseAirMin": 2,
            "offenseWaterMax": 3,
            "defenseLightMin": 3,
            "id": "Amulet of Inevitable Betrayal",
            "icon": "https://images.neopets.com/items/bd_haunted_amulet.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Ancient Gnarled Wand",
            "defenseLightMax": 3,
            "offenseDarkMax": 3,
            "effects": [],
            "offenseDarkMin": 3,
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "offenseEarthMax": 2,
            "offenseEarthMin": 2,
            "defenseLightMin": 3,
            "id": "Ancient Gnarled Wand",
            "icon": "https://images.neopets.com/items/bd_hw_wand_ancientgnarled.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Bleached Bone Staff",
            "defenseLightMax": 3,
            "defensePhysicalMax": 3,
            "effects": [],
            "offenseEarthMax": 5,
            "offenseEarthMin": 5,
            "defenseLightMin": 3,
            "defensePhysicalMin": 3,
            "id": "Bleached Bone Staff",
            "icon": "https://images.neopets.com/items/bd_hw_staff_bleachbone.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Blunted Qasalan Gladius Sword",
            "offensePhysicalMin": 3,
            "defenseEarthMax": 3,
            "effects": [],
            "offensePhysicalMax": 3,
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "offenseEarthMax": 2,
            "defenseEarthMin": 3,
            "offenseEarthMin": 2,
            "id": "Blunted Qasalan Gladius Sword",
            "icon": "https://images.neopets.com/items/bd_qs_gladius.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Bubble Wands",
            "effects": [],
            "offenseWaterMin": 3,
            "offenseAirMax": 3,
            "defenseAirMin": 3,
            "offenseAirMin": 3,
            "offenseLightMin": 3,
            "defenseAirMax": 3,
            "offenseWaterMax": 3,
            "offenseLightMax": 3,
            "id": "Bubble Wands",
            "icon": "https://images.neopets.com/items/wea_bubble_wands.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Chain Spear",
            "defensePhysicalMax": 3,
            "offensePhysicalMin": 6,
            "effects": [],
            "offensePhysicalMax": 6,
            "defensePhysicalMin": 3,
            "id": "Chain Spear",
            "icon": "https://images.neopets.com/items/Chain-Spear.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Chia Skunk Tail",
            "defensePhysicalMax": 3,
            "effects": [],
            "offenseAirMax": 6,
            "offenseAirMin": 6,
            "defensePhysicalMin": 3,
            "id": "Chia Skunk Tail",
            "icon": "https://images.neopets.com/items/bd_chia_skunktail.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Cloudy Wand of Storms",
            "offenseFireMin": 2.6,
            "defenseEarthMax": 3,
            "offenseDarkMax": 2.6,
            "effects": [],
            "offenseWaterMin": 2,
            "offenseDarkMin": 2.6,
            "offenseFireMax": 2.6,
            "defenseEarthMin": 3,
            "offenseWaterMax": 2,
            "id": "Cloudy Wand of Storms",
            "icon": "https://images.neopets.com/items/bd_wand_storm.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Deadly Pugio",
            "offenseFireMin": 2,
            "defenseLightMax": 3,
            "offensePhysicalMin": 0.5,
            "defenseEarthMax": 3,
            "effects": [],
            "offensePhysicalMax": 5,
            "offenseFireMax": 2,
            "offenseEarthMax": 2,
            "defenseEarthMin": 3,
            "offenseEarthMin": 2,
            "defenseLightMin": 3,
            "id": "Deadly Pugio",
            "icon": "https://images.neopets.com/items/ala_pugio_deadly.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Devious Top Hat and Cane",
            "defenseLightMax": 2.6,
            "defensePhysicalMax": 5.2,
            "offensePhysicalMin": 2,
            "defenseEarthMax": 2.6,
            "effects": ["Doubles the physical defense (2.6 -> 5.2) when receiving air and physical icons at the same time."],
            "offensePhysicalMax": 2,
            "offenseAirMax": 2,
            "offenseAirMin": 2,
            "defenseFireMin": 2.6,
            "defenseEarthMin": 2.6,
            "defenseLightMin": 2.6,
            "defensePhysicalMin": 2.6,
            "id": "Devious Top Hat and Cane",
            "icon": "https://images.neopets.com/items/bd_tophat_cane.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Elegant Desert Sword",
            "defenseFireMax": 3,
            "offensePhysicalMin": 3,
            "effects": [],
            "offensePhysicalMax": 3,
            "offenseAirMax": 2,
            "offenseAirMin": 2,
            "defenseFireMin": 3,
            "offenseEarthMax": 2,
            "offenseEarthMin": 2,
            "defenseLightMin": 3,
            "id": "Elegant Desert Sword",
            "icon": "https://images.neopets.com/items/bd_qasala_elegdesertsword.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Florins Flask",
            "effects": [],
            "defenseAirMin": 5,
            "offenseEarthMax": 5,
            "offenseEarthMin": 5,
            "defenseAirMax": 5,
            "id": "Florins Flask",
            "icon": "https://images.neopets.com/items/alm_flask_florins.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Flotsam Ice Shell",
            "defenseFireMax": 3,
            "defenseEarthMax": 2,
            "effects": [],
            "offenseWaterMin": 3,
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "defenseFireMin": 0.3,
            "defenseEarthMin": 2,
            "offenseWaterMax": 3,
            "id": "Flotsam Ice Shell",
            "icon": "https://images.neopets.com/items/bd_flotsam_bluepower.gif",
            "tags": ["L54", "multi-duty", "flotsam"]
        },
        {
            "name": "Frozen Wand of Crystals",
            "offenseFireMin": 2,
            "defenseWaterMin": 3,
            "defenseWaterMax": 3,
            "effects": [],
            "offenseAirMax": 2.667,
            "offenseAirMin": 2.667,
            "offenseLightMin": 3,
            "offenseFireMax": 2,
            "offenseLightMax": 3,
            "id": "Frozen Wand of Crystals",
            "icon": "https://images.neopets.com/items/bd_wand_crystal.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Frozen Water Daggers",
            "defenseWaterMin": 2,
            "defenseWaterMax": 2,
            "effects": [],
            "offenseWaterMin": 3,
            "offenseAirMax": 2,
            "defenseAirMin": 2,
            "offenseAirMin": 2,
            "offenseEarthMax": 3,
            "offenseEarthMin": 3,
            "defenseAirMax": 2,
            "offenseWaterMax": 3,
            "id": "Frozen Water Daggers",
            "icon": "https://images.neopets.com/items/bd_dagger_frzwater.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Frozen Wave Scimitar",
            "defenseLightMax": 2,
            "defensePhysicalMax": 3,
            "offensePhysicalMin": 2,
            "effects": [],
            "offenseWaterMin": 3,
            "offensePhysicalMax": 2,
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "offenseWaterMax": 3,
            "defenseLightMin": 2,
            "defensePhysicalMin": 3,
            "id": "Frozen Wave Scimitar",
            "icon": "https://images.neopets.com/items/bd_scimitar_frzwave.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Ghostly Jetsam Sword",
            "offensePhysicalMin": 3,
            "defenseEarthMax": 3,
            "offenseDarkMax": 2,
            "effects": [],
            "offenseWaterMin": 2,
            "offensePhysicalMax": 3,
            "offenseDarkMin": 2,
            "defenseEarthMin": 3,
            "offenseWaterMax": 2,
            "id": "Ghostly Jetsam Sword",
            "icon": "https://images.neopets.com/items/bd_hw_sword_jetsam.gif",
            "tags": ["L54", "multi-duty", "jetsam"]
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 0,
            "name": "Gilded War Hammer",
            "defenseWaterMin": 0,
            "defenseWaterMax": 0,
            "defenseLightMax": 0,
            "defenseDarkMax": 3,
            "defensePhysicalMax": 0,
            "offensePhysicalMin": 3,
            "defenseEarthMax": 0,
            "offenseDarkMax": 0,
            "effects": [],
            "offenseWaterMin": 0,
            "offensePhysicalMax": 3,
            "offenseDarkMin": 0,
            "offenseAirMax": 2,
            "defenseAirMin": 0,
            "offenseAirMin": 2,
            "defenseFireMin": 0,
            "offenseLightMin": 3,
            "offenseFireMax": 0,
            "offenseEarthMax": 0,
            "defenseEarthMin": 3,
            "offenseEarthMin": 0,
            "defenseAirMax": 0,
            "defenseDarkMin": 0,
            "offenseWaterMax": 0,
            "defenseLightMin": 0,
            "offenseLightMax": 3,
            "defensePhysicalMin": 0,
            "id": "Gilded War Hammer"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 0,
            "name": "Glaive of Verdancy",
            "defenseWaterMin": 0,
            "defenseWaterMax": 0,
            "defenseLightMax": 0,
            "defenseDarkMax": 5,
            "defensePhysicalMax": 0,
            "offensePhysicalMin": 0,
            "defenseEarthMax": 0,
            "offenseDarkMax": 0,
            "effects": [],
            "offenseWaterMin": 0,
            "offensePhysicalMax": 0,
            "offenseDarkMin": 0,
            "offenseAirMax": 3,
            "defenseAirMin": 0,
            "offenseAirMin": 3,
            "defenseFireMin": 0,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 5,
            "defenseEarthMin": 5,
            "offenseEarthMin": 5,
            "defenseAirMax": 0,
            "defenseDarkMin": 0,
            "offenseWaterMax": 0,
            "defenseLightMin": 0,
            "offenseLightMax": 0,
            "defensePhysicalMin": 0,
            "id": "Glaive of Verdancy"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 0,
            "name": "Golden Coin Amulet",
            "defenseWaterMin": 3,
            "defenseWaterMax": 0,
            "defenseLightMax": 3,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 0,
            "offensePhysicalMin": 0,
            "defenseEarthMax": 2,
            "offenseDarkMax": 2,
            "effects": [],
            "offenseWaterMin": 0,
            "offensePhysicalMax": 0,
            "offenseDarkMin": 2,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 2,
            "offenseLightMin": 3,
            "offenseFireMax": 0,
            "offenseEarthMax": 0,
            "defenseEarthMin": 0,
            "offenseEarthMin": 0,
            "defenseAirMax": 0,
            "defenseDarkMin": 0,
            "offenseWaterMax": 0,
            "defenseLightMin": 0,
            "offenseLightMax": 3,
            "defensePhysicalMin": 0,
            "id": "Golden Coin Amulet"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 3,
            "name": "Golden Compass",
            "defenseWaterMin": 0,
            "defenseWaterMax": 0,
            "defenseLightMax": 0,
            "defenseDarkMax": 2.667,
            "defensePhysicalMax": 0,
            "offensePhysicalMin": 0,
            "defenseEarthMax": 0,
            "offenseDarkMax": 0,
            "effects": [],
            "offenseWaterMin": 0,
            "offensePhysicalMax": 0,
            "offenseDarkMin": 0,
            "offenseAirMax": 3,
            "defenseAirMin": 0,
            "offenseAirMin": 3,
            "defenseFireMin": 0,
            "offenseLightMin": 3,
            "offenseFireMax": 3,
            "offenseEarthMax": 0,
            "defenseEarthMin": 2.667,
            "offenseEarthMin": 0,
            "defenseAirMax": 0,
            "defenseDarkMin": 0,
            "offenseWaterMax": 0,
            "defenseLightMin": 0,
            "offenseLightMax": 3,
            "defensePhysicalMin": 0,
            "id": "Golden Compass"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 0,
            "name": "Golden Geraptiku Talisman",
            "defenseWaterMin": 0,
            "defenseWaterMax": 0,
            "defenseLightMax": 0,
            "defenseDarkMax": 3,
            "defensePhysicalMax": 0,
            "offensePhysicalMin": 0,
            "defenseEarthMax": 3,
            "offenseDarkMax": 3,
            "effects": [],
            "offenseWaterMin": 0,
            "offensePhysicalMax": 0,
            "offenseDarkMin": 3,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 3,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 0,
            "defenseEarthMin": 3,
            "offenseEarthMin": 0,
            "defenseAirMax": 0,
            "defenseDarkMin": 0,
            "offenseWaterMax": 0,
            "defenseLightMin": 0,
            "offenseLightMax": 0,
            "defensePhysicalMin": 0,
            "id": "Golden Geraptiku Talisman"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 0,
            "name": "Greater Air Potion",
            "defenseWaterMin": 0,
            "defenseWaterMax": 0,
            "defenseLightMax": 0,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 0,
            "offensePhysicalMin": 0,
            "defenseEarthMax": 0,
            "offenseDarkMax": 0,
            "effects": [],
            "offenseWaterMin": 0,
            "offensePhysicalMax": 0,
            "offenseDarkMin": 0,
            "offenseAirMax": 7,
            "defenseAirMin": 0,
            "offenseAirMin": 7,
            "defenseFireMin": 0,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 0,
            "defenseEarthMin": 0,
            "offenseEarthMin": 0,
            "defenseAirMax": 3,
            "defenseDarkMin": 3,
            "offenseWaterMax": 0,
            "defenseLightMin": 0,
            "offenseLightMax": 0,
            "defensePhysicalMin": 0,
            "id": "Greater Air Potion"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 0,
            "name": "Greater Water Potion",
            "defenseWaterMin": 0,
            "defenseWaterMax": 3,
            "defenseLightMax": 0,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 0,
            "offensePhysicalMin": 0,
            "defenseEarthMax": 0,
            "offenseDarkMax": 0,
            "effects": [],
            "offenseWaterMin": 7,
            "offensePhysicalMax": 0,
            "offenseDarkMin": 0,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 0,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 0,
            "defenseEarthMin": 0,
            "offenseEarthMin": 0,
            "defenseAirMax": 0,
            "defenseDarkMin": 0,
            "offenseWaterMax": 7,
            "defenseLightMin": 0,
            "offenseLightMax": 0,
            "defensePhysicalMin": 3,
            "id": "Greater Water Potion"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 0,
            "name": "Haunted Skull Fan",
            "defenseWaterMin": 0,
            "defenseWaterMax": 0,
            "defenseLightMax": 0,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 3,
            "offensePhysicalMin": 0,
            "defenseEarthMax": 0,
            "offenseDarkMax": 0,
            "effects": [],
            "offenseWaterMin": 0,
            "offensePhysicalMax": 0,
            "offenseDarkMin": 0,
            "offenseAirMax": 6,
            "defenseAirMin": 0,
            "offenseAirMin": 6,
            "defenseFireMin": 0,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 0,
            "defenseEarthMin": 0,
            "offenseEarthMin": 0,
            "defenseAirMax": 0,
            "defenseDarkMin": 0,
            "offenseWaterMax": 0,
            "defenseLightMin": 0,
            "offenseLightMax": 0,
            "defensePhysicalMin": 0,
            "id": "Haunted Skull Fan"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 0,
            "name": "Ice Dagger",
            "defenseWaterMin": 0,
            "defenseWaterMax": 0,
            "defenseLightMax": 0,
            "defenseDarkMax": 3,
            "defensePhysicalMax": 3,
            "offensePhysicalMin": 0.3,
            "defenseEarthMax": 0,
            "offenseDarkMax": 0,
            "effects": [],
            "offenseWaterMin": 3,
            "offensePhysicalMax": 3,
            "offenseDarkMin": 0,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 0,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 0,
            "defenseEarthMin": 3,
            "offenseEarthMin": 0,
            "defenseAirMax": 0,
            "defenseDarkMin": 0,
            "offenseWaterMax": 3,
            "defenseLightMin": 0,
            "offenseLightMax": 0,
            "defensePhysicalMin": 0,
            "id": "Ice Dagger"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 0,
            "name": "Iron Lupe Helm (Lupe)",
            "defenseWaterMin": 3,
            "defenseWaterMax": 0,
            "defenseLightMax": 3,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 0,
            "offensePhysicalMin": 0,
            "defenseEarthMax": 0,
            "offenseDarkMax": 6,
            "effects": [],
            "offenseWaterMin": 0,
            "offensePhysicalMax": 0,
            "offenseDarkMin": 6,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 0,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 0,
            "defenseEarthMin": 0,
            "offenseEarthMin": 0,
            "defenseAirMax": 0,
            "defenseDarkMin": 0,
            "offenseWaterMax": 0,
            "defenseLightMin": 0,
            "offenseLightMax": 0,
            "defensePhysicalMin": 0,
            "id": "Iron Lupe Helm (Lupe)"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 0,
            "name": "Jhudoras Cursed Sword",
            "defenseWaterMin": 5,
            "defenseWaterMax": 0,
            "defenseLightMax": 5,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 0,
            "offensePhysicalMin": 0,
            "defenseEarthMax": 0,
            "offenseDarkMax": 3,
            "effects": [],
            "offenseWaterMin": 2,
            "offensePhysicalMax": 0,
            "offenseDarkMin": 3,
            "offenseAirMax": 2,
            "defenseAirMin": 0,
            "offenseAirMin": 2,
            "defenseFireMin": 0,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 0,
            "defenseEarthMin": 0,
            "offenseEarthMin": 0,
            "defenseAirMax": 0,
            "defenseDarkMin": 0,
            "offenseWaterMax": 2,
            "defenseLightMin": 0,
            "offenseLightMax": 0,
            "defensePhysicalMin": 0,
            "id": "Jhudoras Cursed Sword"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 2,
            "name": "Kau Knight Helmet (Kau)",
            "defenseWaterMin": 0,
            "defenseWaterMax": 0,
            "defenseLightMax": 0,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 0.3,
            "offensePhysicalMin": 0.3,
            "defenseEarthMax": 3,
            "offenseDarkMax": 0,
            "effects": [],
            "offenseWaterMin": 0,
            "offensePhysicalMax": 3,
            "offenseDarkMin": 0,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 3,
            "offenseLightMin": 0,
            "offenseFireMax": 2,
            "offenseEarthMax": 3,
            "defenseEarthMin": 0,
            "offenseEarthMin": 3,
            "defenseAirMax": 0,
            "defenseDarkMin": 0,
            "offenseWaterMax": 0,
            "defenseLightMin": 0,
            "offenseLightMax": 0,
            "defensePhysicalMin": 0,
            "id": "Kau Knight Helmet (Kau)"
        },
        {
            "defenseFireMax": 3,
            "offenseFireMin": 0,
            "name": "Kiko Battle Legs (Kiko)",
            "defenseWaterMin": 0,
            "defenseWaterMax": 0,
            "defenseLightMax": 0,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 0,
            "offensePhysicalMin": 3,
            "defenseEarthMax": 0,
            "offenseDarkMax": 0,
            "effects": [],
            "offenseWaterMin": 0,
            "offensePhysicalMax": 3,
            "offenseDarkMin": 0,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 0,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 3,
            "defenseEarthMin": 0,
            "offenseEarthMin": 3,
            "defenseAirMax": 3,
            "defenseDarkMin": 3,
            "offenseWaterMax": 0,
            "defenseLightMin": 3,
            "offenseLightMax": 0,
            "defensePhysicalMin": 0,
            "id": "Kiko Battle Legs (Kiko)"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 0,
            "name": "Kikovision Goggles (Kiko)",
            "defenseWaterMin": 0,
            "defenseWaterMax": 0,
            "defenseLightMax": 0,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 0,
            "offensePhysicalMin": 0,
            "defenseEarthMax": 3,
            "offenseDarkMax": 0,
            "effects": [],
            "offenseWaterMin": 6,
            "offensePhysicalMax": 0,
            "offenseDarkMin": 0,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 3,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 0,
            "defenseEarthMin": 0,
            "offenseEarthMin": 0,
            "defenseAirMax": 0,
            "defenseDarkMin": 0,
            "offenseWaterMax": 6,
            "defenseLightMin": 0,
            "offenseLightMax": 0,
            "defensePhysicalMin": 0,
            "id": "Kikovision Goggles (Kiko)"
        },
        {
            "defenseFireMax": 3,
            "offenseFireMin": 0,
            "name": "Lightweight Black Tunic (150 INT)",
            "defenseWaterMin": 3,
            "defenseWaterMax": 0,
            "defenseLightMax": 3,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 0,
            "offensePhysicalMin": 0,
            "defenseEarthMax": 0,
            "offenseDarkMax": 5,
            "effects": [],
            "offenseWaterMin": 0,
            "offensePhysicalMax": 0,
            "offenseDarkMin": 0,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 0,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 0,
            "defenseEarthMin": 0,
            "offenseEarthMin": 0,
            "defenseAirMax": 0,
            "defenseDarkMin": 0,
            "offenseWaterMax": 0,
            "defenseLightMin": 3,
            "offenseLightMax": 0,
            "defensePhysicalMin": 0,
            "id": "Lightweight Black Tunic (150 INT)"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 0,
            "name": "Makeshift Ships Hammer",
            "defenseWaterMin": 0,
            "defenseWaterMax": 0,
            "defenseLightMax": 0,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 3,
            "offensePhysicalMin": 3,
            "defenseEarthMax": 0,
            "offenseDarkMax": 0,
            "effects": [],
            "offenseWaterMin": 0,
            "offensePhysicalMax": 3,
            "offenseDarkMin": 0,
            "offenseAirMax": 2,
            "defenseAirMin": 0,
            "offenseAirMin": 2,
            "defenseFireMin": 0,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 3,
            "defenseEarthMin": 0,
            "offenseEarthMin": 3,
            "defenseAirMax": 0,
            "defenseDarkMin": 0,
            "offenseWaterMax": 0,
            "defenseLightMin": 0,
            "offenseLightMax": 0,
            "defensePhysicalMin": 0,
            "id": "Makeshift Ships Hammer"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 5,
            "name": "Moehog Eye Guards (Moehog)",
            "defenseWaterMin": 0,
            "defenseWaterMax": 3,
            "defenseLightMax": 0,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 0,
            "offensePhysicalMin": 0,
            "defenseEarthMax": 0,
            "offenseDarkMax": 0,
            "effects": [],
            "offenseWaterMin": 0,
            "offensePhysicalMax": 0,
            "offenseDarkMin": 0,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 0,
            "offenseLightMin": 0,
            "offenseFireMax": 5,
            "offenseEarthMax": 0,
            "defenseEarthMin": 0,
            "offenseEarthMin": 0,
            "defenseAirMax": 0,
            "defenseDarkMin": 0,
            "offenseWaterMax": 0,
            "defenseLightMin": 0,
            "offenseLightMax": 0,
            "defensePhysicalMin": 3,
            "id": "Moehog Eye Guards (Moehog)"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 0,
            "name": "Mynci Helmet (Mynci)",
            "defenseWaterMin": 3,
            "defenseWaterMax": 0,
            "defenseLightMax": 3,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 3,
            "offensePhysicalMin": 0,
            "defenseEarthMax": 0,
            "offenseDarkMax": 5,
            "effects": [],
            "offenseWaterMin": 0,
            "offensePhysicalMax": 0,
            "offenseDarkMin": 5,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 0,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 0,
            "defenseEarthMin": 0,
            "offenseEarthMin": 0,
            "defenseAirMax": 0,
            "defenseDarkMin": 0,
            "offenseWaterMax": 0,
            "defenseLightMin": 0,
            "offenseLightMax": 0,
            "defensePhysicalMin": 0,
            "id": "Mynci Helmet (Mynci)"
        },
        {
            "defenseFireMax": 2,
            "offenseFireMin": 0,
            "name": "Nightsteed Mace",
            "defenseWaterMin": 0,
            "defenseWaterMax": 0,
            "defenseLightMax": 0,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 0,
            "offensePhysicalMin": 2,
            "defenseEarthMax": 3,
            "offenseDarkMax": 0,
            "effects": [],
            "offenseWaterMin": 0,
            "offensePhysicalMax": 2,
            "offenseDarkMin": 0,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 3,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 3,
            "defenseEarthMin": 0,
            "offenseEarthMin": 3,
            "defenseAirMax": 0,
            "defenseDarkMin": 0,
            "offenseWaterMax": 0,
            "defenseLightMin": 2,
            "offenseLightMax": 0,
            "defensePhysicalMin": 0,
            "id": "Nightsteed Mace"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 0,
            "name": "Oversized Maractite Rune Sword",
            "defenseWaterMin": 0,
            "defenseWaterMax": 3,
            "defenseLightMax": 0,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 0,
            "offensePhysicalMin": 2,
            "defenseEarthMax": 0,
            "offenseDarkMax": 0,
            "effects": [],
            "offenseWaterMin": 3,
            "offensePhysicalMax": 2,
            "offenseDarkMin": 0,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 0,
            "offenseLightMin": 2,
            "offenseFireMax": 0,
            "offenseEarthMax": 0,
            "defenseEarthMin": 0,
            "offenseEarthMin": 0,
            "defenseAirMax": 0,
            "defenseDarkMin": 0,
            "offenseWaterMax": 3,
            "defenseLightMin": 0,
            "offenseLightMax": 2,
            "defensePhysicalMin": 3,
            "id": "Oversized Maractite Rune Sword"
        },
        {
            "defenseFireMax": 2,
            "offenseFireMin": 6,
            "name": "Parachute Dynamite",
            "defenseWaterMin": 0,
            "defenseWaterMax": 0,
            "defenseLightMax": 0,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 0,
            "offensePhysicalMin": 0,
            "defenseEarthMax": 0,
            "offenseDarkMax": 0,
            "effects": [],
            "offenseWaterMin": 0,
            "offensePhysicalMax": 0,
            "offenseDarkMin": 0,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 0,
            "offenseLightMin": 0,
            "offenseFireMax": 6,
            "offenseEarthMax": 0,
            "defenseEarthMin": 0,
            "offenseEarthMin": 0,
            "defenseAirMax": 0,
            "defenseDarkMin": 0,
            "offenseWaterMax": 0,
            "defenseLightMin": 2,
            "offenseLightMax": 0,
            "defensePhysicalMin": 0,
            "id": "Parachute Dynamite"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 0,
            "name": "Phial of the Dreamer",
            "defenseWaterMin": 0,
            "defenseWaterMax": 0,
            "defenseLightMax": 0,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 5,
            "offensePhysicalMin": 0,
            "defenseEarthMax": 0,
            "offenseDarkMax": 0,
            "effects": [],
            "offenseWaterMin": 0,
            "offensePhysicalMax": 0,
            "offenseDarkMin": 0,
            "offenseAirMax": 5,
            "defenseAirMin": 0,
            "offenseAirMin": 5,
            "defenseFireMin": 0,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 0,
            "defenseEarthMin": 0,
            "offenseEarthMin": 0,
            "defenseAirMax": 0,
            "defenseDarkMin": 0,
            "offenseWaterMax": 0,
            "defenseLightMin": 0,
            "offenseLightMax": 0,
            "defensePhysicalMin": 0,
            "id": "Phial of the Dreamer"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 3,
            "name": "Plush Gelert Collar (Gelert)",
            "defenseWaterMin": 0,
            "defenseWaterMax": 3,
            "defenseLightMax": 0,
            "defenseDarkMax": 3,
            "defensePhysicalMax": 0,
            "offensePhysicalMin": 0,
            "defenseEarthMax": 0,
            "offenseDarkMax": 0,
            "effects": [],
            "offenseWaterMin": 0,
            "offensePhysicalMax": 0,
            "offenseDarkMin": 0,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 0,
            "offenseLightMin": 3,
            "offenseFireMax": 3,
            "offenseEarthMax": 0,
            "defenseEarthMin": 3,
            "offenseEarthMin": 0,
            "defenseAirMax": 0,
            "defenseDarkMin": 0,
            "offenseWaterMax": 0,
            "defenseLightMin": 0,
            "offenseLightMax": 3,
            "defensePhysicalMin": 3,
            "id": "Plush Gelert Collar (Gelert)"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 0,
            "name": "Pyon Stinger Mace",
            "defenseWaterMin": 0,
            "defenseWaterMax": 0,
            "defenseLightMax": 0,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 0,
            "offensePhysicalMin": 3,
            "defenseEarthMax": 5,
            "offenseDarkMax": 0,
            "effects": [],
            "offenseWaterMin": 3,
            "offensePhysicalMax": 3,
            "offenseDarkMin": 0,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 5,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 0,
            "defenseEarthMin": 0,
            "offenseEarthMin": 0,
            "defenseAirMax": 0,
            "defenseDarkMin": 0,
            "offenseWaterMax": 3,
            "defenseLightMin": 0,
            "offenseLightMax": 0,
            "defensePhysicalMin": 0,
            "id": "Pyon Stinger Mace"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 0,
            "name": "Rusty Lamppost",
            "defenseWaterMin": 0,
            "defenseWaterMax": 0,
            "defenseLightMax": 0,
            "defenseDarkMax": 2.714,
            "defensePhysicalMax": 2.714,
            "defenseEarthMax": 0,
            "offensePhysicalMin": 0,
            "offenseDarkMax": 0,
            "effects": [],
            "offensePhysicalMax": 0,
            "offenseWaterMin": 0,
            "offenseDarkMin": 0,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 0,
            "offenseLightMin": 5,
            "offenseFireMax": 0,
            "offenseEarthMax": 0,
            "defenseEarthMin": 2.714,
            "offenseEarthMin": 0,
            "defenseAirMax": 0,
            "offenseWaterMax": 0,
            "defenseDarkMin": 0,
            "defenseLightMin": 0,
            "offenseLightMax": 5,
            "defensePhysicalMin": 0,
            "id": "Rusty Lamppost"
        },
        {
            "defenseFireMax": 3,
            "offenseFireMin": 0,
            "name": "Scarab Ring",
            "defenseWaterMin": 0,
            "defenseWaterMax": 0,
            "defenseLightMax": 0,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 3,
            "defenseEarthMax": 0,
            "offensePhysicalMin": 2,
            "offenseDarkMax": 2,
            "effects": [],
            "offensePhysicalMax": 2,
            "offenseWaterMin": 2,
            "offenseDarkMin": 2,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 0,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 0,
            "defenseEarthMin": 0,
            "offenseEarthMin": 0,
            "defenseAirMax": 0,
            "offenseWaterMax": 2,
            "defenseDarkMin": 0,
            "defenseLightMin": 3,
            "offenseLightMax": 0,
            "defensePhysicalMin": 0,
            "id": "Scarab Ring"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 0,
            "name": "Seti Hilt Sword",
            "defenseWaterMin": 0,
            "defenseWaterMax": 0,
            "defenseLightMax": 0,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 3,
            "defenseEarthMax": 0,
            "offensePhysicalMin": 0.3,
            "offenseDarkMax": 0,
            "effects": [],
            "offensePhysicalMax": 3,
            "offenseWaterMin": 0,
            "offenseDarkMin": 0,
            "offenseAirMax": 3,
            "defenseAirMin": 0,
            "offenseAirMin": 3,
            "defenseFireMin": 0,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 3,
            "defenseEarthMin": 0,
            "offenseEarthMin": 3,
            "defenseAirMax": 0,
            "offenseWaterMax": 0,
            "defenseDarkMin": 0,
            "defenseLightMin": 0,
            "offenseLightMax": 0,
            "defensePhysicalMin": 0,
            "id": "Seti Hilt Sword"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 3,
            "name": "Silver Korbat Amulet (Korbat)",
            "defenseWaterMin": 3,
            "defenseWaterMax": 0,
            "defenseLightMax": 3,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 0,
            "defenseEarthMax": 3,
            "offensePhysicalMin": 0,
            "offenseDarkMax": 3,
            "effects": [],
            "offensePhysicalMax": 0,
            "offenseWaterMin": 0,
            "offenseDarkMin": 3,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 3,
            "offenseLightMin": 0,
            "offenseFireMax": 3,
            "offenseEarthMax": 0,
            "defenseEarthMin": 0,
            "offenseEarthMin": 0,
            "defenseAirMax": 0,
            "offenseWaterMax": 0,
            "defenseDarkMin": 0,
            "defenseLightMin": 0,
            "offenseLightMax": 0,
            "defensePhysicalMin": 0,
            "id": "Silver Korbat Amulet (Korbat)"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 3,
            "name": "Sinister Scythe",
            "defenseWaterMin": 5,
            "defenseWaterMax": 0,
            "defenseLightMax": 5,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 0,
            "defenseEarthMax": 0,
            "offensePhysicalMin": 0,
            "offenseDarkMax": 5,
            "effects": [],
            "offensePhysicalMax": 0,
            "offenseWaterMin": 0,
            "offenseDarkMin": 5,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 0,
            "offenseLightMin": 0,
            "offenseFireMax": 3,
            "offenseEarthMax": 0,
            "defenseEarthMin": 0,
            "offenseEarthMin": 0,
            "defenseAirMax": 0,
            "offenseWaterMax": 0,
            "defenseDarkMin": 0,
            "defenseLightMin": 0,
            "offenseLightMax": 0,
            "defensePhysicalMin": 0,
            "id": "Sinister Scythe"
        },
        {
            "defenseFireMax": 3,
            "offenseFireMin": 0,
            "name": "Snowager Sword",
            "defenseWaterMin": 0,
            "defenseWaterMax": 0,
            "defenseLightMax": 0,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 0,
            "defenseEarthMax": 0,
            "offensePhysicalMin": 3,
            "offenseDarkMax": 0,
            "effects": [],
            "offensePhysicalMax": 3,
            "offenseWaterMin": 2,
            "offenseDarkMin": 0,
            "offenseAirMax": 2,
            "defenseAirMin": 0,
            "offenseAirMin": 2,
            "defenseFireMin": 0,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 0,
            "defenseEarthMin": 0,
            "offenseEarthMin": 0,
            "defenseAirMax": 0,
            "offenseWaterMax": 2,
            "defenseDarkMin": 0,
            "defenseLightMin": 3,
            "offenseLightMax": 0,
            "defensePhysicalMin": 0,
            "id": "Snowager Sword"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 0,
            "name": "Sophies Wooden Spoon",
            "defenseWaterMin": 0,
            "defenseWaterMax": 5,
            "defenseLightMax": 0,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 0,
            "defenseEarthMax": 0,
            "offensePhysicalMin": 0,
            "offenseDarkMax": 0,
            "effects": [],
            "offensePhysicalMax": 0,
            "offenseWaterMin": 0,
            "offenseDarkMin": 0,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 0,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 5.6,
            "defenseEarthMin": 0,
            "offenseEarthMin": 5.6,
            "defenseAirMax": 0,
            "offenseWaterMax": 0,
            "defenseDarkMin": 0,
            "defenseLightMin": 0,
            "offenseLightMax": 0,
            "defensePhysicalMin": 5,
            "id": "Sophies Wooden Spoon"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 0,
            "name": "Spiked Negg Mace",
            "defenseWaterMin": 0,
            "defenseWaterMax": 0,
            "defenseLightMax": 0,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 0,
            "defenseEarthMax": 5,
            "offensePhysicalMin": 0,
            "offenseDarkMax": 0,
            "effects": [],
            "offensePhysicalMax": 0,
            "offenseWaterMin": 0,
            "offenseDarkMin": 0,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 5,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 5,
            "defenseEarthMin": 0,
            "offenseEarthMin": 5,
            "defenseAirMax": 0,
            "offenseWaterMax": 0,
            "defenseDarkMin": 0,
            "defenseLightMin": 0,
            "offenseLightMax": 0,
            "defensePhysicalMin": 0,
            "id": "Spiked Negg Mace"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 0,
            "name": "Sword of the Dead",
            "defenseWaterMin": 5,
            "defenseWaterMax": 0,
            "defenseLightMax": 5,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 0,
            "defenseEarthMax": 0,
            "offensePhysicalMin": 0,
            "offenseDarkMax": 3,
            "effects": [],
            "offensePhysicalMax": 0,
            "offenseWaterMin": 0,
            "offenseDarkMin": 3,
            "offenseAirMax": 2.6,
            "defenseAirMin": 0,
            "offenseAirMin": 2.6,
            "defenseFireMin": 0,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 0,
            "defenseEarthMin": 0,
            "offenseEarthMin": 0,
            "defenseAirMax": 0,
            "offenseWaterMax": 0,
            "defenseDarkMin": 0,
            "defenseLightMin": 0,
            "offenseLightMax": 0,
            "defensePhysicalMin": 0,
            "id": "Sword of the Dead"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 3,
            "name": "The Scimitar of Lyra",
            "defenseWaterMin": 0,
            "defenseWaterMax": 0,
            "defenseLightMax": 0,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 2.66,
            "defenseEarthMax": 0,
            "offensePhysicalMin": 0,
            "offenseDarkMax": 0,
            "effects": [],
            "offensePhysicalMax": 0,
            "offenseWaterMin": 0,
            "offenseDarkMin": 0,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 0,
            "offenseLightMin": 6,
            "offenseFireMax": 3,
            "offenseEarthMax": 0,
            "defenseEarthMin": 0,
            "offenseEarthMin": 0,
            "defenseAirMax": 0,
            "offenseWaterMax": 0,
            "defenseDarkMin": 0,
            "defenseLightMin": 0,
            "offenseLightMax": 6,
            "defensePhysicalMin": 0,
            "id": "The Scimitar of Lyra"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 0,
            "name": "Tooth of Terask",
            "defenseWaterMin": 0,
            "defenseWaterMax": 0,
            "defenseLightMax": 0,
            "defenseDarkMax": 3,
            "defensePhysicalMax": 0,
            "defenseEarthMax": 0,
            "offensePhysicalMin": 0,
            "offenseDarkMax": 0,
            "effects": [],
            "offensePhysicalMax": 0,
            "offenseWaterMin": 3,
            "offenseDarkMin": 0,
            "offenseAirMax": 3,
            "defenseAirMin": 0,
            "offenseAirMin": 3,
            "defenseFireMin": 0,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 0,
            "defenseEarthMin": 3,
            "offenseEarthMin": 0,
            "defenseAirMax": 0,
            "offenseWaterMax": 3,
            "defenseDarkMin": 0,
            "defenseLightMin": 0,
            "offenseLightMax": 0,
            "defensePhysicalMin": 0,
            "id": "Tooth of Terask"
        },
        {
            "defenseFireMax": 3,
            "offenseFireMin": 0,
            "name": "Twisted Dark Dagger",
            "defenseWaterMin": 3,
            "defenseWaterMax": 0,
            "defenseLightMax": 3,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 0,
            "defenseEarthMax": 0,
            "offensePhysicalMin": 0.3,
            "offenseDarkMax": 3,
            "effects": [],
            "offensePhysicalMax": 3,
            "offenseWaterMin": 0,
            "offenseDarkMin": 3,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 0,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 2,
            "defenseEarthMin": 0,
            "offenseEarthMin": 2,
            "defenseAirMax": 0,
            "offenseWaterMax": 0,
            "defenseDarkMin": 0,
            "defenseLightMin": 3,
            "offenseLightMax": 0,
            "defensePhysicalMin": 0,
            "id": "Twisted Dark Dagger"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 0,
            "name": "Ultimate Negg Hammer",
            "defenseWaterMin": 3,
            "defenseWaterMax": 0,
            "defenseLightMax": 3,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 0,
            "defenseEarthMax": 0,
            "offensePhysicalMin": 5,
            "offenseDarkMax": 0,
            "effects": [],
            "offensePhysicalMax": 5,
            "offenseWaterMin": 0,
            "offenseDarkMin": 0,
            "offenseAirMax": 3,
            "defenseAirMin": 0,
            "offenseAirMin": 3,
            "defenseFireMin": 0,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 0,
            "defenseEarthMin": 0,
            "offenseEarthMin": 0,
            "defenseAirMax": 0,
            "offenseWaterMax": 0,
            "defenseDarkMin": 0,
            "defenseLightMin": 0,
            "offenseLightMax": 0,
            "defensePhysicalMin": 0,
            "id": "Ultimate Negg Hammer"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 0,
            "name": "Ultra Supreme Kiko Walker (Kiko)",
            "defenseWaterMin": 0,
            "defenseWaterMax": 0,
            "defenseLightMax": 0,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 0,
            "defenseEarthMax": 3,
            "offensePhysicalMin": 2.65,
            "offenseDarkMax": 0,
            "effects": [],
            "offensePhysicalMax": 2.65,
            "offenseWaterMin": 0,
            "offenseDarkMin": 0,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 3,
            "offenseLightMin": 2.65,
            "offenseFireMax": 0,
            "offenseEarthMax": 0,
            "defenseEarthMin": 0,
            "offenseEarthMin": 0,
            "defenseAirMax": 2,
            "offenseWaterMax": 0,
            "defenseDarkMin": 0,
            "defenseLightMin": 0,
            "offenseLightMax": 2.65,
            "defensePhysicalMin": 0,
            "id": "Ultra Supreme Kiko Walker (Kiko)"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 2,
            "name": "Wand of the Moon",
            "defenseWaterMin": 0,
            "defenseWaterMax": 0,
            "defenseLightMax": 0,
            "defenseDarkMax": 3,
            "defensePhysicalMax": 0,
            "defenseEarthMax": 0,
            "offensePhysicalMin": 0,
            "offenseDarkMax": 0,
            "effects": [],
            "offensePhysicalMax": 0,
            "offenseWaterMin": 0,
            "offenseDarkMin": 0,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 0,
            "offenseLightMin": 2,
            "offenseFireMax": 2,
            "offenseEarthMax": 3,
            "defenseEarthMin": 3,
            "offenseEarthMin": 3,
            "defenseAirMax": 0,
            "offenseWaterMax": 0,
            "defenseDarkMin": 0,
            "defenseLightMin": 0,
            "offenseLightMax": 2,
            "defensePhysicalMin": 0,
            "id": "Wand of the Moon"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 0,
            "name": "Zombie Fist on a Stick",
            "defenseWaterMin": 0,
            "defenseWaterMax": 0,
            "defenseLightMax": 0,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 5,
            "defenseEarthMax": 0,
            "offensePhysicalMin": 3,
            "offenseDarkMax": 0,
            "effects": [],
            "offensePhysicalMax": 3,
            "offenseWaterMin": 0,
            "offenseDarkMin": 0,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 0,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 3,
            "defenseEarthMin": 0,
            "offenseEarthMin": 3,
            "defenseAirMax": 0,
            "offenseWaterMax": 0,
            "defenseDarkMin": 0,
            "defenseLightMin": 0,
            "offenseLightMax": 0,
            "defensePhysicalMin": 0,
            "id": "Zombie Fist on a Stick"
        },
        {
            "defenseFireMax": 5,
            "offenseFireMin": 0,
            "name": "Wand of Lameness",
            "defenseWaterMin": 0,
            "defenseWaterMax": 0,
            "defenseLightMax": 0,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 0,
            "defenseEarthMax": 0,
            "offensePhysicalMin": 0,
            "offenseDarkMax": 0,
            "effects": [],
            "offensePhysicalMax": 0,
            "offenseWaterMin": 0,
            "offenseDarkMin": 0,
            "offenseAirMax": 3,
            "defenseAirMin": 0,
            "offenseAirMin": 3,
            "defenseFireMin": 0,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 3,
            "defenseEarthMin": 0,
            "offenseEarthMin": 3,
            "defenseAirMax": 0,
            "offenseWaterMax": 0,
            "defenseDarkMin": 0,
            "defenseLightMin": 5,
            "offenseLightMax": 0,
            "defensePhysicalMin": 0,
            "id": "Wand of Lameness"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 0,
            "name": "Grimoire of Thade",
            "defenseWaterMin": 0,
            "defenseWaterMax": 0,
            "defenseLightMax": 0,
            "defenseDarkMax": 5,
            "defensePhysicalMax": 0,
            "defenseEarthMax": 0,
            "offensePhysicalMin": 0.3,
            "offenseDarkMax": 5,
            "effects": [],
            "offensePhysicalMax": 3,
            "offenseWaterMin": 0,
            "offenseDarkMin": 5,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 0,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 0,
            "defenseEarthMin": 5,
            "offenseEarthMin": 0,
            "defenseAirMax": 0,
            "offenseWaterMax": 0,
            "defenseDarkMin": 0,
            "defenseLightMin": 0,
            "offenseLightMax": 0,
            "defensePhysicalMin": 0,
            "id": "Grimoire of Thade"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 0,
            "name": "Asparagus Dagger",
            "defenseWaterMin": 0,
            "defenseWaterMax": 0,
            "defenseLightMax": 0,
            "defenseDarkMax": 5,
            "defensePhysicalMax": 0,
            "defenseEarthMax": 0,
            "offensePhysicalMin": 0.3,
            "offenseDarkMax": 0,
            "effects": [],
            "offensePhysicalMax": 3,
            "offenseWaterMin": 0,
            "offenseDarkMin": 0,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 0,
            "offenseLightMin": 3,
            "offenseFireMax": 0,
            "offenseEarthMax": 3,
            "defenseEarthMin": 5,
            "offenseEarthMin": 3,
            "defenseAirMax": 0,
            "offenseWaterMax": 0,
            "defenseDarkMin": 0,
            "defenseLightMin": 0,
            "offenseLightMax": 3,
            "defensePhysicalMin": 0,
            "id": "Asparagus Dagger"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 0,
            "name": "Hansos Masamune",
            "defenseWaterMin": 0,
            "defenseWaterMax": 0,
            "defenseLightMax": 0,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 3,
            "defenseEarthMax": 0,
            "offensePhysicalMin": 5,
            "offenseDarkMax": 0,
            "effects": [],
            "offensePhysicalMax": 5,
            "offenseWaterMin": 0,
            "offenseDarkMin": 0,
            "offenseAirMax": 3,
            "defenseAirMin": 0,
            "offenseAirMin": 3,
            "defenseFireMin": 0,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 0,
            "defenseEarthMin": 0,
            "offenseEarthMin": 0,
            "defenseAirMax": 0,
            "offenseWaterMax": 0,
            "defenseDarkMin": 0,
            "defenseLightMin": 0,
            "offenseLightMax": 0,
            "defensePhysicalMin": 0,
            "id": "Hansos Masamune"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 3,
            "name": "Amulet of the Unblinking Eye",
            "defenseWaterMin": 2,
            "defenseWaterMax": 0,
            "defenseLightMax": 2,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 0,
            "defenseEarthMax": 0,
            "offensePhysicalMin": 0,
            "offenseDarkMax": 3,
            "effects": [],
            "offensePhysicalMax": 0,
            "offenseWaterMin": 0,
            "offenseDarkMin": 3,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 0,
            "offenseLightMin": 3,
            "offenseFireMax": 3,
            "offenseEarthMax": 0,
            "defenseEarthMin": 0,
            "offenseEarthMin": 0,
            "defenseAirMax": 0,
            "offenseWaterMax": 0,
            "defenseDarkMin": 0,
            "defenseLightMin": 0,
            "offenseLightMax": 3,
            "defensePhysicalMin": 0,
            "id": "Amulet of the Unblinking Eye"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 0,
            "name": "Dusty Magic Broom!",
            "defenseWaterMin": 5,
            "defenseWaterMax": 0,
            "defenseLightMax": 5,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 0,
            "defenseEarthMax": 0,
            "offensePhysicalMin": 0,
            "offenseDarkMax": 0,
            "effects": [],
            "offensePhysicalMax": 0,
            "offenseWaterMin": 0,
            "offenseDarkMin": 0,
            "offenseAirMax": 3,
            "defenseAirMin": 0,
            "offenseAirMin": 3,
            "defenseFireMin": 0,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 5,
            "defenseEarthMin": 0,
            "offenseEarthMin": 5,
            "defenseAirMax": 0,
            "offenseWaterMax": 0,
            "defenseDarkMin": 0,
            "defenseLightMin": 0,
            "offenseLightMax": 0,
            "defensePhysicalMin": 0,
            "id": "Dusty Magic Broom!"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 0,
            "name": "Glaive of Verdancy",
            "defenseWaterMin": 0,
            "defenseWaterMax": 0,
            "defenseLightMax": 0,
            "defenseDarkMax": 5,
            "defensePhysicalMax": 0,
            "defenseEarthMax": 0,
            "offensePhysicalMin": 0,
            "offenseDarkMax": 0,
            "effects": [],
            "offensePhysicalMax": 0,
            "offenseWaterMin": 0,
            "offenseDarkMin": 0,
            "offenseAirMax": 3,
            "defenseAirMin": 0,
            "offenseAirMin": 3,
            "defenseFireMin": 0,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 5,
            "defenseEarthMin": 5,
            "offenseEarthMin": 5,
            "defenseAirMax": 0,
            "offenseWaterMax": 0,
            "defenseDarkMin": 0,
            "defenseLightMin": 0,
            "offenseLightMax": 0,
            "defensePhysicalMin": 0,
            "id": "Glaive of Verdancy"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 3,
            "name": "Sinister Scythe",
            "defenseWaterMin": 5,
            "defenseWaterMax": 0,
            "defenseLightMax": 5,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 0,
            "defenseEarthMax": 0,
            "offensePhysicalMin": 0,
            "offenseDarkMax": 5,
            "effects": [],
            "offensePhysicalMax": 0,
            "offenseWaterMin": 0,
            "offenseDarkMin": 5,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 0,
            "offenseLightMin": 0,
            "offenseFireMax": 3,
            "offenseEarthMax": 0,
            "defenseEarthMin": 0,
            "offenseEarthMin": 0,
            "defenseAirMax": 0,
            "offenseWaterMax": 0,
            "defenseDarkMin": 0,
            "defenseLightMin": 0,
            "offenseLightMax": 0,
            "defensePhysicalMin": 0,
            "id": "Sinister Scythe"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 3,
            "name": "Space Faerie Token",
            "defenseWaterMin": 0,
            "defenseWaterMax": 0,
            "defenseLightMax": 0,
            "defenseDarkMax": 5,
            "defensePhysicalMax": 0,
            "defenseEarthMax": 0,
            "offensePhysicalMin": 0,
            "offenseDarkMax": 0,
            "effects": [],
            "offensePhysicalMax": 0,
            "offenseWaterMin": 0,
            "offenseDarkMin": 0,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 0,
            "offenseLightMin": 5,
            "offenseFireMax": 3,
            "offenseEarthMax": 0,
            "defenseEarthMin": 5,
            "offenseEarthMin": 0,
            "defenseAirMax": 0,
            "offenseWaterMax": 0,
            "defenseDarkMin": 0,
            "defenseLightMin": 0,
            "offenseLightMax": 5,
            "defensePhysicalMin": 0,
            "id": "Space Faerie Token"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 3,
            "name": "Fighting Folder (+2hp)",
            "defenseWaterMin": 0,
            "defenseWaterMax": 0,
            "defenseLightMax": 0,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 0,
            "defenseEarthMax": 0,
            "offensePhysicalMin": 0.3,
            "offenseDarkMax": 0,
            "effects": [],
            "offensePhysicalMax": 3,
            "offenseWaterMin": 0,
            "offenseDarkMin": 0,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 0,
            "offenseLightMin": 0,
            "offenseFireMax": 3,
            "offenseEarthMax": 2,
            "defenseEarthMin": 0,
            "offenseEarthMin": 2,
            "defenseAirMax": 0,
            "offenseWaterMax": 0,
            "defenseDarkMin": 0,
            "defenseLightMin": 0,
            "offenseLightMax": 0,
            "defensePhysicalMin": 0,
            "id": "Fighting Folder (+2hp)"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 0,
            "name": "Sunblade Replica (def when dark)",
            "defenseWaterMin": 2,
            "defenseWaterMax": 0,
            "defenseLightMax": 2,
            "defenseDarkMax": 2,
            "defensePhysicalMax": 2,
            "defenseEarthMax": 2,
            "offensePhysicalMin": 0.3,
            "offenseDarkMax": 0,
            "effects": [],
            "offensePhysicalMax": 3,
            "offenseWaterMin": 0,
            "offenseDarkMin": 0,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 2,
            "offenseLightMin": 3,
            "offenseFireMax": 0,
            "offenseEarthMax": 0,
            "defenseEarthMin": 2,
            "offenseEarthMin": 0,
            "defenseAirMax": 2,
            "offenseWaterMax": 0,
            "defenseDarkMin": 2,
            "defenseLightMin": 0,
            "offenseLightMax": 3,
            "defensePhysicalMin": 0,
            "id": "Sunblade Replica (def when dark)"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 0,
            "name": "Downsize! Reduces all damage by 50%",
            "defenseWaterMin": 0,
            "defenseWaterMax": 0,
            "defenseLightMax": 0,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 0,
            "defenseEarthMax": 0,
            "offensePhysicalMin": 0,
            "offenseDarkMax": 0,
            "effects": [],
            "offensePhysicalMax": 0,
            "offenseWaterMin": 0,
            "offenseDarkMin": 0,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 0,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 0,
            "defenseEarthMin": 0,
            "offenseEarthMin": 0,
            "defenseAirMax": 0,
            "offenseWaterMax": 0,
            "defenseDarkMin": 0,
            "defenseLightMin": 0,
            "offenseLightMax": 0,
            "defensePhysicalMin": 0,
            "id": "Downsize! Reduces all damage by 50%"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 0,
            "name": "Pretty Negg Shield",
            "defenseWaterMin": 0,
            "defenseWaterMax": 0,
            "defenseLightMax": 0,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 0,
            "defenseEarthMax": 0,
            "offensePhysicalMin": 0,
            "offenseDarkMax": 0,
            "effects": [
              "Blocks 60% of Earth and Light damage.",
              "Reflects 20% of Earth and Light damage back to the attacker."
            ],
            "percentageEarthBlocked": 60,
            "percentageLightBlocked": 60,
            "percentageEarthReflected": 20,
            "percentageLightReflected": 20,
            "offensePhysicalMax": 0,
            "offenseWaterMin": 0,
            "offenseDarkMin": 0,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 0,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 0,
            "defenseEarthMin": 0,
            "offenseEarthMin": 0,
            "defenseAirMax": 0,
            "offenseWaterMax": 0,
            "defenseDarkMin": 0,
            "defenseLightMin": 0,
            "offenseLightMax": 0,
            "defensePhysicalMin": 0,
            "id": "Pretty Negg Shield. Blocks 60% Earth/Light"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 0,
            "name": "Nebula Force Field Generator",
            "defenseWaterMin": 3,
            "defenseWaterMax": 0,
            "defenseLightMax": 3,
            "defenseDarkMax": 3,
            "defensePhysicalMax": 3,
            "defenseEarthMax": 0,
            "offensePhysicalMin": 0,
            "offenseDarkMax": 0,
            "effects": [],
            "offensePhysicalMax": 0,
            "offenseWaterMin": 0,
            "offenseDarkMin": 0,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 0,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 0,
            "defenseEarthMin": 3,
            "offenseEarthMin": 0,
            "defenseAirMax": 3,
            "offenseWaterMax": 0,
            "defenseDarkMin": 3,
            "defenseLightMin": 0,
            "offenseLightMax": 0,
            "defensePhysicalMin": 0,
            "id": "Nebula Force Field Generator"
        },
        {
            "defenseFireMax": 3,
            "offenseFireMin": 0,
            "name": "Sophies Magic Hat",
            "defenseWaterMin": 0,
            "defenseWaterMax": 0,
            "defenseLightMax": 0,
            "defenseDarkMax": 3,
            "defensePhysicalMax": 3,
            "defenseEarthMax": 5,
            "offensePhysicalMin": 0,
            "offenseDarkMax": 0,
            "effects": [],
            "offensePhysicalMax": 0,
            "offenseWaterMin": 0,
            "offenseDarkMin": 0,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 0,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 0,
            "defenseEarthMin": 3,
            "offenseEarthMin": 0,
            "defenseAirMax": 0,
            "offenseWaterMax": 0,
            "defenseDarkMin": 0,
            "defenseLightMin": 0,
            "offenseLightMax": 0,
            "defensePhysicalMin": 0,
            "id": "Sophies Magic Hat"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 0,
            "name": "Kiko Skull Pirate Hat",
            "defenseWaterMin": 0,
            "defenseWaterMax": 5,
            "defenseLightMax": 0,
            "defenseDarkMax": 5,
            "defensePhysicalMax": 2,
            "defenseEarthMax": 0,
            "offensePhysicalMin": 0,
            "offenseDarkMax": 0,
            "effects": [],
            "offensePhysicalMax": 0,
            "offenseWaterMin": 0,
            "offenseDarkMin": 0,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 0,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 0,
            "defenseEarthMin": 5,
            "offenseEarthMin": 0,
            "defenseAirMax": 0,
            "offenseWaterMax": 0,
            "defenseDarkMin": 0,
            "defenseLightMin": 0,
            "offenseLightMax": 0,
            "defensePhysicalMin": 5,
            "id": "Kiko Skull Pirate Hat"
        },
        {
            "defenseFireMax": 3,
            "offenseFireMin": 0,
            "name": "Solar Flare Shield",
            "defenseWaterMin": 0,
            "defenseWaterMax": 3,
            "defenseLightMax": 0,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 3,
            "defenseEarthMax": 0,
            "offensePhysicalMin": 0,
            "offenseDarkMax": 0,
            "effects": [],
            "offensePhysicalMax": 0,
            "offenseWaterMin": 0,
            "offenseDarkMin": 0,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 0,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 0,
            "defenseEarthMin": 0,
            "offenseEarthMin": 0,
            "defenseAirMax": 3,
            "offenseWaterMax": 0,
            "defenseDarkMin": 3,
            "defenseLightMin": 3,
            "offenseLightMax": 0,
            "defensePhysicalMin": 3,
            "id": "Solar Flare Shield"
        },
        {
            "defenseFireMax": 3,
            "offenseFireMin": 0,
            "name": "Wanderers Cloak",
            "defenseWaterMin": 3,
            "defenseWaterMax": 2,
            "defenseLightMax": 3,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 0,
            "defenseEarthMax": 2,
            "offensePhysicalMin": 0,
            "offenseDarkMax": 0,
            "effects": [],
            "offensePhysicalMax": 0,
            "offenseWaterMin": 0,
            "offenseDarkMin": 0,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 5,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 0,
            "defenseEarthMin": 0,
            "offenseEarthMin": 0,
            "defenseAirMax": 2,
            "offenseWaterMax": 0,
            "defenseDarkMin": 2,
            "defenseLightMin": 3,
            "offenseLightMax": 0,
            "defensePhysicalMin": 2,
            "id": "Wanderers Cloak"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 0,
            "name": "Leaf Shield",
            "defenseWaterMin": 0,
            "defenseWaterMax": 5,
            "defenseLightMax": 0,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 3,
            "defenseEarthMax": 5,
            "offensePhysicalMin": 0,
            "offenseDarkMax": 0,
            "effects": [],
            "offensePhysicalMax": 0,
            "offenseWaterMin": 0,
            "offenseDarkMin": 0,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 5,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 0,
            "defenseEarthMin": 0,
            "offenseEarthMin": 0,
            "defenseAirMax": 0,
            "offenseWaterMax": 0,
            "defenseDarkMin": 0,
            "defenseLightMin": 0,
            "offenseLightMax": 0,
            "defensePhysicalMin": 5,
            "id": "Leaf Shield"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 0,
            "name": "Virtupets X-514 Super Shield",
            "defenseWaterMin": 2,
            "defenseWaterMax": 2,
            "defenseLightMax": 2,
            "defenseDarkMax": 2,
            "defensePhysicalMax": 0.3,
            "defenseEarthMax": 3,
            "offensePhysicalMin": 0,
            "offenseDarkMax": 0,
            "effects": [],
            "offensePhysicalMax": 0,
            "offenseWaterMin": 0,
            "offenseDarkMin": 0,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 3,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 0,
            "defenseEarthMin": 2,
            "offenseEarthMin": 0,
            "defenseAirMax": 0,
            "offenseWaterMax": 0,
            "defenseDarkMin": 0,
            "defenseLightMin": 0,
            "offenseLightMax": 0,
            "defensePhysicalMin": 2,
            "id": "Virtupets X-514 Super Shield"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 0,
            "name": "Parchment Cloak (+150INT)",
            "defenseWaterMin": 3.9,
            "defenseWaterMax": 0,
            "defenseLightMax": 3.9,
            "defenseDarkMax": 4,
            "defensePhysicalMax": 0,
            "defenseEarthMax": 2.6,
            "offensePhysicalMin": 0,
            "offenseDarkMax": 0,
            "effects": [],
            "offensePhysicalMax": 0,
            "offenseWaterMin": 0,
            "offenseDarkMin": 0,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 2.6,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 0,
            "defenseEarthMin": 4,
            "offenseEarthMin": 0,
            "defenseAirMax": 5,
            "offenseWaterMax": 0,
            "defenseDarkMin": 5,
            "defenseLightMin": 0,
            "offenseLightMax": 0,
            "defensePhysicalMin": 0,
            "id": "Parchment Cloak (+150INT)"
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 0,
            "name": "Parasol of Unfortunate Demise",
            "defenseWaterMin": 0,
            "defenseWaterMax": 3,
            "defenseLightMax": 0,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 0,
            "defenseEarthMax": 1.4,
            "offensePhysicalMin": 0,
            "offenseDarkMax": 0,
            "effects": [
                "Blocks 100% of water",
                "Blocks 100% of light"
            ],
            "offensePhysicalMax": 0,
            "offenseWaterMin": 0,
            "offenseDarkMin": 0,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 5,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 0,
            "defenseEarthMin": 0,
            "offenseEarthMin": 0,
            "defenseAirMax": 0,
            "offenseWaterMax": 0,
            "defenseDarkMin": 0,
            "defenseLightMin": 0,
            "offenseLightMax": 0,
            "defensePhysicalMin": 3,
            "id": "Parasol of Unfortunate Demise",
            "percentageWaterBlocked": 100,
            "percentageLightBlocked": 100
        },
        {
            "defenseFireMax": 0,
            "offenseFireMin": 0,
            "name": "Kaylas Magic Cloak (Zafara)",
            "defenseWaterMin": 5,
            "defenseWaterMax": 5,
            "defenseLightMax": 5,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 0,
            "defenseEarthMax": 0,
            "offensePhysicalMin": 0,
            "offenseDarkMax": 0,
            "effects": [],
            "offensePhysicalMax": 0,
            "offenseWaterMin": 0,
            "offenseDarkMin": 0,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 0,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 0,
            "defenseEarthMin": 0,
            "offenseEarthMin": 0,
            "defenseAirMax": 5,
            "offenseWaterMax": 0,
            "defenseDarkMin": 5,
            "defenseLightMin": 0,
            "offenseLightMax": 0,
            "defensePhysicalMin": 5,
            "id": "Kaylas Magic Cloak (Zafara)"
        },
        {
            "defenseFireMax": 3,
            "offenseFireMin": 0,
            "name": "Royal Blue Cape",
            "defenseWaterMin": 3,
            "defenseWaterMax": 0,
            "defenseLightMax": 3,
            "defenseDarkMax": 0,
            "defensePhysicalMax": 0,
            "defenseEarthMax": 3,
            "offensePhysicalMin": 0,
            "offenseDarkMax": 0,
            "effects": [],
            "offensePhysicalMax": 0,
            "offenseWaterMin": 0,
            "offenseDarkMin": 0,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 3,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 0,
            "defenseEarthMin": 0,
            "offenseEarthMin": 0,
            "defenseAirMax": 3,
            "offenseWaterMax": 0,
            "defenseDarkMin": 3,
            "defenseLightMin": 3,
            "offenseLightMax": 0,
            "defensePhysicalMin": 0,
            "id": "Royal Blue Cape"
        },
        {
            "defenseFireMax": 3.27,
            "offenseFireMin": 0,
            "name": "Full Buzz Armour (Buzz)",
            "defenseWaterMin": 0,
            "defenseWaterMax": 0,
            "defenseLightMax": 0,
            "defenseDarkMax": 3.27,
            "defensePhysicalMax": 3.27,
            "defenseEarthMax": 3.27,
            "offensePhysicalMin": 0,
            "offenseDarkMax": 0,
            "effects": [],
            "offensePhysicalMax": 0,
            "offenseWaterMin": 0,
            "offenseDarkMin": 0,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 3.27,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 0,
            "defenseEarthMin": 3.27,
            "offenseEarthMin": 0,
            "defenseAirMax": 3.27,
            "offenseWaterMax": 0,
            "defenseDarkMin": 3.24,
            "defenseLightMin": 3.27,
            "offenseLightMax": 0,
            "defensePhysicalMin": 0,
            "id": "Full Buzz Armour (Buzz)"
        },
        {
            "defenseFireMax": 2,
            "offenseFireMin": 0,
            "name": "Tower Shield",
            "defenseWaterMin": 2,
            "defenseWaterMax": 0,
            "defenseLightMax": 2,
            "defenseDarkMax": 2,
            "defensePhysicalMax": 2,
            "defenseEarthMax": 2,
            "offensePhysicalMin": 0,
            "offenseDarkMax": 0,
            "effects": [],
            "offensePhysicalMax": 0,
            "offenseWaterMin": 0,
            "offenseDarkMin": 0,
            "offenseAirMax": 0,
            "defenseAirMin": 0,
            "offenseAirMin": 0,
            "defenseFireMin": 2,
            "offenseLightMin": 0,
            "offenseFireMax": 0,
            "offenseEarthMax": 0,
            "defenseEarthMin": 2,
            "offenseEarthMin": 0,
            "defenseAirMax": 2,
            "offenseWaterMax": 0,
            "defenseDarkMin": 2,
            "defenseLightMin": 2,
            "offenseLightMax": 0,
            "defensePhysicalMin": 0,
            "id": "Tower Shield"
        }
    ],
    "abilities": [
        {
            "id": "Halitosis",
            "name": "Halitosis",
            "effects": [
                "Deals 2 earth damage on this turn and the next turn. 1 turn cooldown after last damage."
            ],
            "offenseEarthMax": 2,
            "offenseEarthMin": 2
        },
        {
            "id": "Static Cling",
            "name": "Static Cling",
            "effects": [
                "Deals 3 light damage on this turn"
            ],
            "offenseLightMax": 3,
            "offenseLightMin": 3
        },
        {
            "id": "Shade",
            "name": "Shade",
            "effects": [
                "Protects 3 icons from 3 different elements for 1 turn, except Physical and Dark. 4 turns cooldown. Note: This ability could protect against glitch darkness but not dark."
            ]
        },
        {
            "id": "Positive Thinking",
            "name": "Positive Thinking",
            "effects": [
                "Restores 5% (Up to 2.7, rounded to 3) of your current HP to your Neopet. Once per battle"
            ]
        }
    ]
};