// This file contains all the item data that would normally be served from the backend

const itemsData = {
    "weapons": [
      {
        "id": "fire-sword",
        "name": "Fire Sword",
        "type": "weapon",
        "slot": "main",
        "minimumFireIcons": 3,
        "maximumFireIcons": 5,
        "minimumWaterIcons": 0,
        "maximumWaterIcons": 0,
        "minimumLightIcons": 1,
        "maximumLightIcons": 2,
        "minimumDarkIcons": 0,
        "maximumDarkIcons": 0,
        "minimumAirIcons": 0,
        "maximumAirIcons": 0,
        "minimumEarthIcons": 0,
        "maximumEarthIcons": 0,
        "minimumPhysicalIcons": 2,
        "maximumPhysicalIcons": 4,
        "specialEffect": "Has a 10% chance to ignite the target"
      },
      {
        "id": "water-staff",
        "name": "Water Staff",
        "type": "weapon",
        "slot": "main",
        "minimumFireIcons": 0,
        "maximumFireIcons": 0,
        "minimumWaterIcons": 4,
        "maximumWaterIcons": 6,
        "minimumLightIcons": 2,
        "maximumLightIcons": 3,
        "minimumDarkIcons": 0,
        "maximumDarkIcons": 0,
        "minimumAirIcons": 1,
        "maximumAirIcons": 2,
        "minimumEarthIcons": 0,
        "maximumEarthIcons": 0,
        "minimumPhysicalIcons": 0,
        "maximumPhysicalIcons": 1,
        "specialEffect": "Heals caster for 5% of damage dealt"
      },
      {
        "id": "earth-shield",
        "name": "Earth Shield",
        "type": "weapon",
        "slot": "offhand",
        "minimumFireIcons": 0,
        "maximumFireIcons": 0,
        "minimumWaterIcons": 0,
        "maximumWaterIcons": 0,
        "minimumLightIcons": 0,
        "maximumLightIcons": 1,
        "minimumDarkIcons": 0,
        "maximumDarkIcons": 0,
        "minimumAirIcons": 0,
        "maximumAirIcons": 0,
        "minimumEarthIcons": 3,
        "maximumEarthIcons": 5,
        "minimumPhysicalIcons": 2,
        "maximumPhysicalIcons": 3,
        "specialEffect": "Reduces incoming physical damage by 20%"
      },
      {
        "id": "dark-dagger",
        "name": "Dark Dagger",
        "type": "weapon",
        "slot": "offhand",
        "minimumFireIcons": 0,
        "maximumFireIcons": 0,
        "minimumWaterIcons": 0,
        "maximumWaterIcons": 0,
        "minimumLightIcons": 0,
        "maximumLightIcons": 0,
        "minimumDarkIcons": 4,
        "maximumDarkIcons": 7,
        "minimumAirIcons": 2,
        "maximumAirIcons": 3,
        "minimumEarthIcons": 0,
        "maximumEarthIcons": 0,
        "minimumPhysicalIcons": 1,
        "maximumPhysicalIcons": 3,
        "specialEffect": "Has a 15% chance to apply a poison effect"
      },
      {
        "id": "light-amulet",
        "name": "Light Amulet",
        "type": "weapon",
        "slot": "accessory",
        "minimumFireIcons": 0,
        "maximumFireIcons": 1,
        "minimumWaterIcons": 0,
        "maximumWaterIcons": 1,
        "minimumLightIcons": 5,
        "maximumLightIcons": 8,
        "minimumDarkIcons": 0,
        "maximumDarkIcons": 0,
        "minimumAirIcons": 1,
        "maximumAirIcons": 2,
        "minimumEarthIcons": 0,
        "maximumEarthIcons": 0,
        "minimumPhysicalIcons": 0,
        "maximumPhysicalIcons": 0,
        "specialEffect": "Increases healing effectiveness by 15%"
      },
      {
        "id": "air-ring",
        "name": "Air Ring",
        "type": "weapon",
        "slot": "accessory",
        "minimumFireIcons": 0,
        "maximumFireIcons": 0,
        "minimumWaterIcons": 1,
        "maximumWaterIcons": 2,
        "minimumLightIcons": 0,
        "maximumLightIcons": 0,
        "minimumDarkIcons": 0,
        "maximumDarkIcons": 0,
        "minimumAirIcons": 4,
        "maximumAirIcons": 6,
        "minimumEarthIcons": 0,
        "maximumEarthIcons": 1,
        "minimumPhysicalIcons": 0,
        "maximumPhysicalIcons": 0,
        "specialEffect": "Increases movement speed by 10%"
      }
    ],
    "abilities": [
      {
        "id": "fireball",
        "name": "Fireball",
        "type": "ability",
        "damageType": "fire",
        "minimumIcons": 5,
        "maximumIcons": 8,
        "effect": "Deals fire damage to target"
      },
      {
        "id": "heal",
        "name": "Healing Light",
        "type": "ability",
        "damageType": "heal",
        "minimumIcons": 4,
        "maximumIcons": 7,
        "effect": "Heals target for light energy"
      },
      {
        "id": "earthquake",
        "name": "Earthquake",
        "type": "ability",
        "damageType": "earth",
        "minimumIcons": 6,
        "maximumIcons": 10,
        "effect": "Deals earth damage to all enemies"
      },
      {
        "id": "lightning-strike",
        "name": "Lightning Strike",
        "type": "ability",
        "damageType": "air",
        "minimumIcons": 7,
        "maximumIcons": 9,
        "effect": "Deals air damage with a chance to stun"
      },
      {
        "id": "shadow-bolt",
        "name": "Shadow Bolt",
        "type": "ability",
        "damageType": "dark",
        "minimumIcons": 5,
        "maximumIcons": 8,
        "effect": "Deals dark damage and drains life"
      }
    ]
  };