// This file reads the data from the items.json file and converts it into a JavaScript object

const itemsData = {
    "weapons": [
        {
            "offenseFireMin": 3,
            "name": "Bow of the Hegelob",
            "effects": [],
            "tags": ["L54", "constant"],
            "offenseWaterMin": 3,
            "offenseFireMax": 3,
            "offenseEarthMax": 3,
            "offenseEarthMin": 3,
            "offenseWaterMax": 3,
            "id": "Bow of the Hegelob",
            "icon": "https://images.neopets.com/items/shw_hegelob_bow.gif"
        },
        {
            "offenseFireMin": 3,
            "name": "Carved Qasalan Blowgun",
            "effects": [],
            "offenseLightMin": 3,
            "offenseFireMax": 3,
            "offenseEarthMax": 3,
            "offenseEarthMin": 3,
            "id": "Carved Qasalan Blowgun",
            "icon": "https://images.neopets.com/items/bd_qs_blowgun.gif",
            "tags": ["L54", "constant"]
        },
        {
            "offenseFireMin": 3,
            "name": "Chia Ray Gun",
            "effects": [],
            "offenseLightMin": 5,
            "offenseFireMax": 3,
            "offenseLightMax": 5,
            "id": "Chia Ray Gun",
            "icon": "https://images.neopets.com/items/bd_chia_raygun.gif",
            "tags": ["L54", "constant", "chia"]
        },
        {
            "name": "Cooty Crossbow",
            "offenseDarkMax": 3,
            "effects": [],
            "offenseWaterMin": 3,
            "offenseDarkMin": 3,
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "offenseWaterMax": 3,
            "id": "Cooty Crossbow",
            "icon": "https://images.neopets.com/items/wea_ddy21_cootycrossbow.gif",
            "tags": ["L54", "constant"]
        },
        {
            "icon": "https://images.neopets.com/items/bd_ddy18_dangerdodgeball.gif",
            "name": "Dangerous Dodgeball",
            "offenseDarkMax": 7,
            "effects": [],
            "offenseDarkMin": 7,
            "id": "Dangerous Dodgeball",
            "tags": ["L54", "constant"]
        },
        {
            "icon": "https://images.neopets.com/items/bd_darkduck.gif",
            "name": "Dark Battle Duck",
            "offenseDarkMax": 3,
            "effects": [],
            "offenseWaterMin": 5,
            "offenseDarkMin": 3,
            "offenseWaterMax": 5,
            "id": "Dark Battle Duck",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Decorative Maractite Sword",
            "offensePhysicalMin": 3,
            "effects": [],
            "offenseWaterMin": 5,
            "offensePhysicalMax": 3,
            "offenseWaterMax": 5,
            "id": "Decorative Maractite Sword",
            "icon": "https://images.neopets.com/items/bd_maractite_sword.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Desert Crossbow",
            "offenseFireMin": 6,
            "effects": [],
            "offenseLightMin": 2,
            "offenseFireMax": 6,
            "offenseLightMax": 2,
            "id": "Desert Crossbow",
            "icon": "https://images.neopets.com/items/wea_tge_dcrossbow.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Dual Batons of Katsuo",
            "offenseFireMin": 2,
            "offensePhysicalMin": 2,
            "offenseDarkMax": 2,
            "effects": [],
            "offensePhysicalMax": 2,
            "offenseDarkMin": 2,
            "offenseFireMax": 2,
            "offenseEarthMax": 3,
            "offenseEarthMin": 3,
            "id": "Dual Batons of Katsuo",
            "icon": "https://images.neopets.com/items/wea_dual_batons.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Essence of Esophagor",
            "effects": [],
            "offenseWaterMin": 4.5,
            "offenseEarthMax": 4.5,
            "offenseEarthMin": 4.5,
            "offenseWaterMax": 4.5,
            "id": "Essence of Esophagor",
            "icon": "https://images.neopets.com/items/bd_esoph_essence.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Exceptionally Tiny Laser Cannon",
            "offensePhysicalMin": 0,
            "effects": [],
            "offenseWaterMin": 2,
            "offenseLightMin": 3,
            "offenseEarthMax": 3,
            "offenseEarthMin": 3,
            "offenseWaterMax": 2,
            "offenseLightMax": 3,
            "id": "Exceptionally Tiny Laser Cannon",
            "icon": "https://images.neopets.com/items/ros_bd_tinylaser.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Festive Cutlass",
            "offenseFireMin": 5,
            "offenseDarkMax": 3,
            "effects": [],
            "offenseDarkMin": 3,
            "offenseFireMax": 5,
            "id": "Festive Cutlass",
            "icon": "https://images.neopets.com/items/festive_cutlass.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Ice Club",
            "offensePhysicalMin": 3,
            "effects": [],
            "offenseWaterMin": 3,
            "offensePhysicalMax": 3,
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "offenseWaterMax": 3,
            "id": "Ice Club",
            "icon": "https://images.neopets.com/items/bd_ice_cube_club.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Kazeriu Whip",
            "offensePhysicalMin": 3,
            "effects": [],
            "offensePhysicalMax": 3,
            "offenseAirMax": 5,
            "offenseAirMin": 5,
            "id": "Kazeriu Whip",
            "icon": "https://images.neopets.com/items/shw_whip_kazeriu.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Korbat Power Blaster",
            "effects": [],
            "offenseWaterMin": 3,
            "offenseAirMax": 5,
            "offenseAirMin": 5,
            "offenseWaterMax": 3,
            "id": "Korbat Power Blaster",
            "icon": "https://images.neopets.com/items/bd_korblaster.gif",
            "tags": ["L54", "constant", "korbat"]
        },
        {
            "name": "Lavaball",
            "offenseFireMin": 6,
            "effects": [],
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "offenseFireMax": 6,
            "id": "Lavaball",
            "icon": "https://images.neopets.com/items/toy_lavaball.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Lutari Lance",
            "offensePhysicalMin": 3,
            "effects": [],
            "offensePhysicalMax": 3,
            "offenseAirMax": 2.66,
            "offenseAirMin": 2.66,
            "offenseEarthMax": 3,
            "offenseEarthMin": 3,
            "id": "Lutari Lance",
            "icon": "https://images.neopets.com/items/bd_lutari_lance.gif",
            "tags": ["L54", "constant", "lutari"]
        },
        {
            "name": "Merciless Idiom",
            "offenseDarkMax": 3,
            "effects": [],
            "offenseDarkMin": 3,
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "offenseLightMin": 3,
            "offenseLightMax": 3,
            "id": "Merciless Idiom",
            "icon": "https://images.neopets.com/items/wea_thruster.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Night Katana",
            "offensePhysicalMin": 3,
            "offenseDarkMax": 3,
            "effects": [],
            "offensePhysicalMax": 3,
            "offenseDarkMin": 3,
            "offenseAirMax": 2,
            "offenseAirMin": 2,
            "id": "Night Katana",
            "icon": "https://images.neopets.com/items/bd_blue_katana.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Pickle Spear",
            "effects": [],
            "offenseEarthMax": 8,
            "offenseEarthMin": 8,
            "id": "Pickle Spear",
            "icon": "https://images.neopets.com/items/bd_pickle_spear.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Pike Pike",
            "effects": [],
            "offenseWaterMin": 4.5,
            "offenseLightMin": 4.5,
            "offenseWaterMax": 4.5,
            "offenseLightMax": 4.5,
            "id": "Pike Pike",
            "icon": "https://images.neopets.com/items/bd_pike_pike.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Psellias Fighting Fan",
            "offensePhysicalMin": 3,
            "effects": [],
            "offensePhysicalMax": 3,
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "offenseLightMin": 3,
            "offenseLightMax": 3,
            "id": "Psellias Fighting Fan",
            "icon": "https://images.neopets.com/items/bd_airfaerie_purplefan.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Rainbow Scroll",
            "effects": [],
            "offenseWaterMin": 3,
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "offenseLightMin": 3,
            "offenseWaterMax": 3,
            "offenseLightMax": 3,
            "id": "Rainbow Scroll",
            "icon": "https://images.neopets.com/items/bvs_rainbow_scroll.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Ridiculously Heavy Battle Hammer",
            "offensePhysicalMin": 3,
            "effects": [],
            "offensePhysicalMax": 3,
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "offenseEarthMax": 3,
            "offenseEarthMin": 3,
            "id": "Ridiculously Heavy Battle Hammer",
            "icon": "https://images.neopets.com/items/bd_heavybattlehammer.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Rusty Cleaver",
            "offenseFireMin": 6,
            "offensePhysicalMin": 3,
            "effects": [],
            "offensePhysicalMax": 3,
            "offenseFireMax": 6,
            "id": "Rusty Cleaver",
            "icon": "https://images.neopets.com/items/bd_hw_cleaver_rusty.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Scroll of Forgotten Promises",
            "offenseDarkMax": 3,
            "effects": [],
            "offenseDarkMin": 3,
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "offenseEarthMax": 2,
            "offenseEarthMin": 2,
            "id": "Scroll of Forgotten Promises",
            "icon": "https://images.neopets.com/items/bvs_scroll_forgottenpromises.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Scroll of the Battlefield",
            "offensePhysicalMin": 6,
            "effects": [],
            "offensePhysicalMax": 6,
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "id": "Scroll of the Battlefield",
            "icon": "https://images.neopets.com/items/bvs_thebattlefield.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Scroll of the Earth",
            "effects": [],
            "offenseWaterMin": 2.6,
            "offenseEarthMax": 6,
            "offenseWaterMax": 2.6,
            "id": "Scroll of the Earth",
            "icon": "https://images.neopets.com/items/bvs_earth_scroll.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Shuko",
            "effects": [],
            "offenseWaterMin": 7,
            "offenseWaterMax": 7,
            "id": "Shuko",
            "icon": "https://images.neopets.com/items/shw_shuko.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Silver Draik Bow",
            "offenseFireMin": 3,
            "offensePhysicalMin": 3,
            "effects": [],
            "offensePhysicalMax": 3,
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "offenseFireMax": 3,
            "id": "Silver Draik Bow",
            "icon": "https://images.neopets.com/items/bd_draik_bow.gif",
            "tags": ["L54", "constant", "draik"]
        },
        {
            "name": "Skeletal Fire Gun",
            "offenseFireMin": 6,
            "effects": [],
            "offenseLightMin": 2,
            "offenseFireMax": 6,
            "offenseLightMax": 2,
            "id": "Skeletal Fire Gun",
            "icon": "https://images.neopets.com/items/bd_haunted_firegun.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Spearmint",
            "effects": [],
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "offenseEarthMax": 5,
            "offenseEarthMin": 5,
            "id": "Spearmint",
            "icon": "https://images.neopets.com/items/bd_spearmint.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Stone Club",
            "offensePhysicalMin": 3,
            "effects": [],
            "offensePhysicalMax": 3,
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "offenseEarthMax": 3,
            "offenseEarthMin": 3,
            "id": "Stone Club",
            "icon": "https://images.neopets.com/items/bd_tyr_club.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Strange Marking Stone Necklace",
            "effects": [],
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "offenseLightMin": 3,
            "offenseEarthMax": 3,
            "offenseEarthMin": 3,
            "offenseLightMax": 3,
            "id": "Strange Marking Stone Necklace",
            "icon": "https://images.neopets.com/items/bd_necklace_strangestone.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Throwing Cutlass",
            "effects": [],
            "offenseWaterMin": 3,
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "offenseEarthMax": 3,
            "offenseEarthMin": 3,
            "offenseWaterMax": 3,
            "id": "Throwing Cutlass",
            "icon": "https://images.neopets.com/items/bd_gmc_cutlass_throwing.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Tuskaninny Battle Trumpet",
            "effects": [],
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "offenseEarthMax": 5,
            "offenseEarthMin": 5,
            "id": "Tuskaninny Battle Trumpet",
            "icon": "https://images.neopets.com/items/bd_tusk_straw.gif",
            "tags": ["L54", "constant", "tuskaninny"]
        },
        {
            "name": "Water Bazooka",
            "offensePhysicalMin": 4,
            "effects": [],
            "offensePhysicalMax": 4,
            "offenseWaterMin": 4,
            "offenseWaterMax": 4,
            "id": "Water Bazooka",
            "icon": "https://images.neopets.com/items/bd_ddy18_waterbazooka.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Sword of Elements",
            "offenseFireMin": 2,
            "offenseDarkMax": 2,
            "effects": [],
            "offenseDarkMin": 2,
            "offenseAirMax": 2,
            "offenseAirMin": 2,
            "offenseLightMin": 2,
            "offenseFireMax": 2,
            "offenseLightMax": 2,
            "id": "Sword of Elements",
            "icon": "https://images.neopets.com/items/bd_gmc2013_rainswrd.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Pumpkin Stick",
            "effects": [],
            "offenseLightMin": 8,
            "offenseLightMax": 8,
            "id": "Pumpkin Stick",
            "icon": "https://images.neopets.com/items/bd_pumpkin_stick.gif",
            "tags": ["L54", "constant"]
        },
        {
            "name": "Altadorian Swordbreaker",
            "effects": [
                "Blocks 100% of physical"
            ],
            "offenseEarthMax": 5,
            "offenseEarthMin": 5,
            "id": "Altadorian Swordbreaker",
            "percentagePhysicalBlocked": 100,
            "icon": "https://images.neopets.com/items/ala_sword_altadbreak.gif",
            "tags": ["L54", "blocker", "multi-duty"]
        },
        {
            "name": "Amulet of Altador",
            "defenseWaterMin": 3,
            "defenseWaterMax": 3,
            "defenseDarkMax": 3,
            "effects": [],
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "offenseLightMin": 3,
            "defenseDarkMin": 3,
            "offenseLightMax": 3,
            "id": "Amulet of Altador",
            "icon": "https://images.neopets.com/items/bd_amulet_of_altador.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Amulet of Inevitable Betrayal",
            "defenseLightMax": 3,
            "offenseDarkMax": 2,
            "effects": [],
            "offenseWaterMin": 3,
            "offenseDarkMin": 2,
            "offenseAirMax": 2,
            "offenseAirMin": 2,
            "offenseWaterMax": 3,
            "defenseLightMin": 3,
            "id": "Amulet of Inevitable Betrayal",
            "icon": "https://images.neopets.com/items/bd_haunted_amulet.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Ancient Gnarled Wand",
            "defenseLightMax": 3,
            "offenseDarkMax": 3,
            "effects": [],
            "offenseDarkMin": 3,
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "offenseEarthMax": 2,
            "offenseEarthMin": 2,
            "defenseLightMin": 3,
            "id": "Ancient Gnarled Wand",
            "icon": "https://images.neopets.com/items/bd_hw_wand_ancientgnarled.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Bleached Bone Staff",
            "defenseLightMax": 3,
            "defensePhysicalMax": 3,
            "effects": [],
            "offenseEarthMax": 5,
            "offenseEarthMin": 5,
            "defenseLightMin": 3,
            "defensePhysicalMin": 3,
            "id": "Bleached Bone Staff",
            "icon": "https://images.neopets.com/items/bd_hw_staff_bleachbone.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Blunted Qasalan Gladius Sword",
            "offensePhysicalMin": 3,
            "defenseEarthMax": 3,
            "effects": [],
            "offensePhysicalMax": 3,
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "offenseEarthMax": 2,
            "defenseEarthMin": 3,
            "offenseEarthMin": 2,
            "id": "Blunted Qasalan Gladius Sword",
            "icon": "https://images.neopets.com/items/bd_qs_gladius.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Bubble Wands",
            "effects": [],
            "offenseWaterMin": 3,
            "offenseAirMax": 3,
            "defenseAirMin": 3,
            "offenseAirMin": 3,
            "offenseLightMin": 3,
            "defenseAirMax": 3,
            "offenseWaterMax": 3,
            "offenseLightMax": 3,
            "id": "Bubble Wands",
            "icon": "https://images.neopets.com/items/wea_bubble_wands.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Chain Spear",
            "defensePhysicalMax": 3,
            "offensePhysicalMin": 6,
            "effects": [],
            "offensePhysicalMax": 6,
            "defensePhysicalMin": 3,
            "id": "Chain Spear",
            "icon": "https://images.neopets.com/items/Chain-Spear.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Chia Skunk Tail",
            "defensePhysicalMax": 3,
            "effects": [],
            "offenseAirMax": 6,
            "offenseAirMin": 6,
            "defensePhysicalMin": 3,
            "id": "Chia Skunk Tail",
            "icon": "https://images.neopets.com/items/bd_chia_skunktail.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Cloudy Wand of Storms",
            "offenseFireMin": 2.6,
            "defenseEarthMax": 3,
            "offenseDarkMax": 2.6,
            "effects": [],
            "offenseWaterMin": 2,
            "offenseDarkMin": 2.6,
            "offenseFireMax": 2.6,
            "defenseEarthMin": 3,
            "offenseWaterMax": 2,
            "id": "Cloudy Wand of Storms",
            "icon": "https://images.neopets.com/items/bd_wand_storm.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Deadly Pugio",
            "offenseFireMin": 2,
            "defenseLightMax": 3,
            "offensePhysicalMin": 0.5,
            "defenseEarthMax": 3,
            "effects": [],
            "offensePhysicalMax": 5,
            "offenseFireMax": 2,
            "offenseEarthMax": 2,
            "defenseEarthMin": 3,
            "offenseEarthMin": 2,
            "defenseLightMin": 3,
            "id": "Deadly Pugio",
            "icon": "https://images.neopets.com/items/ala_pugio_deadly.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Devious Top Hat and Cane",
            "defenseLightMax": 2.6,
            "defensePhysicalMax": 5.2,
            "offensePhysicalMin": 2,
            "defenseEarthMax": 2.6,
            "effects": ["Doubles the physical defense (2.6 -> 5.2) when receiving air and physical icons at the same time."],
            "offensePhysicalMax": 2,
            "offenseAirMax": 2,
            "offenseAirMin": 2,
            "defenseFireMin": 2.6,
            "defenseEarthMin": 2.6,
            "defenseLightMin": 2.6,
            "defensePhysicalMin": 2.6,
            "id": "Devious Top Hat and Cane",
            "icon": "https://images.neopets.com/items/bd_tophat_cane.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Elegant Desert Sword",
            "defenseFireMax": 3,
            "offensePhysicalMin": 3,
            "effects": [],
            "offensePhysicalMax": 3,
            "offenseAirMax": 2,
            "offenseAirMin": 2,
            "defenseFireMin": 3,
            "offenseEarthMax": 2,
            "offenseEarthMin": 2,
            "defenseLightMin": 3,
            "id": "Elegant Desert Sword",
            "icon": "https://images.neopets.com/items/bd_qasala_elegdesertsword.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Florins Flask",
            "effects": [],
            "defenseAirMin": 5,
            "offenseEarthMax": 5,
            "offenseEarthMin": 5,
            "defenseAirMax": 5,
            "id": "Florins Flask",
            "icon": "https://images.neopets.com/items/alm_flask_florins.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Flotsam Ice Shell",
            "defenseFireMax": 3,
            "defenseEarthMax": 2,
            "effects": [],
            "offenseWaterMin": 3,
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "defenseFireMin": 0.3,
            "defenseEarthMin": 2,
            "offenseWaterMax": 3,
            "id": "Flotsam Ice Shell",
            "icon": "https://images.neopets.com/items/bd_flotsam_bluepower.gif",
            "tags": ["L54", "multi-duty", "flotsam"]
        },
        {
            "name": "Frozen Wand of Crystals",
            "offenseFireMin": 2,
            "defenseWaterMin": 3,
            "defenseWaterMax": 3,
            "effects": [],
            "offenseAirMax": 2.667,
            "offenseAirMin": 2.667,
            "offenseLightMin": 3,
            "offenseFireMax": 2,
            "offenseLightMax": 3,
            "id": "Frozen Wand of Crystals",
            "icon": "https://images.neopets.com/items/bd_wand_crystal.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Frozen Water Daggers",
            "defenseWaterMin": 2,
            "defenseWaterMax": 2,
            "effects": [],
            "offenseWaterMin": 3,
            "offenseAirMax": 2,
            "defenseAirMin": 2,
            "offenseAirMin": 2,
            "offenseEarthMax": 3,
            "offenseEarthMin": 3,
            "defenseAirMax": 2,
            "offenseWaterMax": 3,
            "id": "Frozen Water Daggers",
            "icon": "https://images.neopets.com/items/bd_dagger_frzwater.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Frozen Wave Scimitar",
            "defenseLightMax": 2,
            "defensePhysicalMax": 3,
            "offensePhysicalMin": 2,
            "effects": [],
            "offenseWaterMin": 3,
            "offensePhysicalMax": 2,
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "offenseWaterMax": 3,
            "defenseLightMin": 2,
            "defensePhysicalMin": 3,
            "id": "Frozen Wave Scimitar",
            "icon": "https://images.neopets.com/items/bd_scimitar_frzwave.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Ghostly Jetsam Sword",
            "offensePhysicalMin": 3,
            "defenseEarthMax": 3,
            "offenseDarkMax": 2,
            "effects": [],
            "offenseWaterMin": 2,
            "offensePhysicalMax": 3,
            "offenseDarkMin": 2,
            "defenseEarthMin": 3,
            "offenseWaterMax": 2,
            "id": "Ghostly Jetsam Sword",
            "icon": "https://images.neopets.com/items/bd_hw_sword_jetsam.gif",
            "tags": ["L54", "multi-duty", "jetsam"]
        },
        {
            "name": "Gilded War Hammer",
            "defenseDarkMax": 3,
            "offensePhysicalMin": 3,
            "effects": [],
            "offensePhysicalMax": 3,
            "offenseAirMax": 2,
            "offenseAirMin": 2,
            "offenseLightMin": 3,
            "defenseDarkMin": 3,
            "offenseLightMax": 3,
            "id": "Gilded War Hammer",
            "icon": "https://images.neopets.com/items/bd_gildedwarhammer.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Glaive of Verdancy",
            "defenseDarkMax": 5,
            "effects": [],
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "offenseEarthMax": 5,
            "offenseEarthMin": 5,
            "defenseDarkMin": 5,
            "id": "Glaive of Verdancy",
            "icon": "https://images.neopets.com/items/bd_glaiveverd.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Golden Coin Amulet",
            "defenseLightMax": 3,
            "defenseDarkMax": 2,
            "offenseDarkMax": 2,
            "effects": [],
            "offenseDarkMin": 2,
            "offenseLightMin": 3,
            "defenseDarkMin": 2,
            "defenseLightMin": 3,
            "offenseLightMax": 3,
            "id": "Golden Coin Amulet",
            "icon": "https://images.neopets.com/items/wea_goldencoin_amulet.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Golden Compass",
            "offenseFireMin": 3,
            "defenseDarkMax": 2.667,
            "effects": [],
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "offenseLightMin": 3,
            "offenseFireMax": 3,
            "defenseDarkMin": 2.667,
            "offenseLightMax": 3,
            "id": "Golden Compass",
            "icon": "https://images.neopets.com/items/alm_magic_compass.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Golden Geraptiku Talisman",
            "defenseDarkMax": 3,
            "defenseEarthMax": 3,
            "offenseDarkMax": 3,
            "effects": [],
            "offenseDarkMin": 3,
            "defenseEarthMin": 3,
            "defenseDarkMin": 3,
            "id": "Golden Geraptiku Talisman",
            "icon": "https://images.neopets.com/items/bd_ger_goldtalisman.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Greater Air Potion",
            "effects": [],
            "offenseAirMax": 7,
            "defenseAirMin": 3,
            "offenseAirMin": 7,
            "defenseAirMax": 3,
            "id": "Greater Air Potion",
            "icon": "https://images.neopets.com/items/bpo_potion_greater_air.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Greater Water Potion",
            "defenseWaterMin": 3,
            "defenseWaterMax": 3,
            "effects": [],
            "offenseWaterMin": 7,
            "offenseWaterMax": 7,
            "id": "Greater Water Potion",
            "icon": "https://images.neopets.com/items/bpo_potion_greater_water.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Haunted Skull Fan",
            "defensePhysicalMax": 3,
            "effects": [],
            "offenseAirMax": 6,
            "offenseAirMin": 6,
            "defensePhysicalMin": 3,
            "id": "Haunted Skull Fan",
            "icon": "https://images.neopets.com/items/bd_hw_wand_hauntfan.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Ice Dagger",
            "defenseDarkMax": 3,
            "defensePhysicalMax": 3,
            "offensePhysicalMin": 0.3,
            "effects": [],
            "offenseWaterMin": 3,
            "offensePhysicalMax": 3,
            "defenseDarkMin": 3,
            "offenseWaterMax": 3,
            "defensePhysicalMin": 3,
            "id": "Ice Dagger",
            "icon": "https://images.neopets.com/items/bd_icedagger.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Iron Lupe Helm",
            "defenseLightMax": 3,
            "offenseDarkMax": 6,
            "effects": [],
            "offenseDarkMin": 6,
            "defenseLightMin": 3,
            "id": "Iron Lupe Helm",
            "icon": "https://images.neopets.com/items/bd_lupe_helmet.gif",
            "tags": ["L54", "multi-duty", "lupe"]
        },
        {
            "name": "Jhudoras Cursed Sword",
            "defenseLightMax": 5,
            "offenseDarkMax": 3,
            "effects": [],
            "offenseWaterMin": 2,
            "offenseDarkMin": 3,
            "offenseAirMax": 2,
            "offenseAirMin": 2,
            "offenseWaterMax": 2,
            "defenseLightMin": 5,
            "id": "Jhudoras Cursed Sword",
            "icon": "https://images.neopets.com/items/bd_jhudora_cursedsword.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Kau Knight Helmet",
            "offenseFireMin": 2,
            "defensePhysicalMax": 3,
            "offensePhysicalMin": 0.3,
            "defenseEarthMax": 3,
            "effects": [],
            "offensePhysicalMax": 3,
            "offenseFireMax": 2,
            "offenseEarthMax": 3,
            "defenseEarthMin": 3,
            "offenseEarthMin": 3,
            "defensePhysicalMin": 0.3,
            "id": "Kau Knight Helmet",
            "icon": "https://images.neopets.com/items/bd_kau_knighthelmet.gif",
            "tags": ["L54", "multi-duty", "kau"]
        },
        {
            "name": "Kiko Battle Legs",
            "offensePhysicalMin": 3,
            "defenseEarthMax": 3,
            "effects": [],
            "offensePhysicalMax": 3,
            "defenseAirMin": 2,
            "offenseEarthMax": 3,
            "defenseEarthMin": 3,
            "offenseEarthMin": 3,
            "defenseAirMax": 2,
            "id": "Kiko Battle Legs",
            "icon": "https://images.neopets.com/items/bd_kiko_legs.gif",
            "tags": ["L54", "multi-duty", "kiko"]
        },
        {
            "name": "Kikovision Goggles",
            "defenseEarthMax": 3,
            "effects": [],
            "offenseWaterMin": 6,
            "defenseEarthMin": 3,
            "offenseWaterMax": 6,
            "id": "Kikovision Goggles",
            "icon": "https://images.neopets.com/items/bd_kiko_goggles.gif",
            "tags": ["L54", "multi-duty", "kiko"]
        },
        {
            "name": "Lightweight Black Tunic",
            "defenseFireMax": 3,
            "defenseLightMax": 3,
            "offenseDarkMax": 5,
            "effects": ["Deals 5 icons of dark when your pet's intelligence is 150 or more, and your opponent's pet has less than 150 intelligence."],
            "offenseDarkMin": 0,
            "defenseFireMin": 3,
            "defenseLightMin": 3,
            "id": "Lightweight Black Tunic",
            "icon": "https://images.neopets.com/items/bva_lightweight_tunic.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Makeshift Ships Hammer",
            "defensePhysicalMax": 3,
            "offensePhysicalMin": 3,
            "effects": [],
            "offensePhysicalMax": 3,
            "offenseAirMax": 2,
            "offenseAirMin": 2,
            "offenseEarthMax": 3,
            "offenseEarthMin": 3,
            "defensePhysicalMin": 3,
            "id": "Makeshift Ships Hammer",
            "icon": "https://images.neopets.com/items/jli_bd_makeshifthammer.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Moehog Eye Guards",
            "offenseFireMin": 5,
            "defenseWaterMin": 3,
            "defenseWaterMax": 3,
            "effects": [],
            "offenseFireMax": 5,
            "id": "Moehog Eye Guards",
            "icon": "https://images.neopets.com/items/bd_moehog_goggles.gif",
            "tags": ["L54", "multi-duty", "moehog"]
        },
        {
            "name": "Mynci Helmet",
            "defenseLightMax": 3,
            "defensePhysicalMax": 3,
            "offenseDarkMax": 5,
            "effects": [],
            "offenseDarkMin": 5,
            "defenseLightMin": 3,
            "defensePhysicalMin": 3,
            "id": "Mynci Helmet",
            "icon": "https://images.neopets.com/items/bd_mynci_phelm.gif",
            "tags": ["L54", "multi-duty", "mynci"]
        },
        {
            "name": "Nightsteed Mace",
            "defenseFireMax": 2,
            "offensePhysicalMin": 2,
            "defenseEarthMax": 3,
            "effects": [],
            "offensePhysicalMax": 2,
            "defenseFireMin": 2,
            "offenseEarthMax": 3,
            "defenseEarthMin": 3,
            "offenseEarthMin": 3,
            "id": "Nightsteed Mace",
            "icon": "https://images.neopets.com/items/bd_nightsteed_mace.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Oversized Maractite Rune Sword",
            "defenseWaterMin": 3,
            "defenseWaterMax": 3,
            "offensePhysicalMin": 2,
            "effects": [],
            "offenseWaterMin": 3,
            "offensePhysicalMax": 2,
            "offenseLightMin": 2,
            "offenseWaterMax": 3,
            "offenseLightMax": 2,
            "id": "Oversized Maractite Rune Sword",
            "icon": "https://images.neopets.com/items/bd_maractite_ossword.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Parachute Dynamite",
            "defenseFireMax": 2,
            "offenseFireMin": 6,
            "effects": [],
            "defenseFireMin": 2,
            "offenseFireMax": 6,
            "id": "Parachute Dynamite",
            "icon": "https://images.neopets.com/items/wea_y18gmc_para_dynamite.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Phial of the Dreamer",
            "defensePhysicalMax": 5,
            "effects": [],
            "offenseAirMax": 5,
            "offenseAirMin": 5,
            "defensePhysicalMin": 5,
            "id": "Phial of the Dreamer",
            "icon": "https://images.neopets.com/items/alm_phial_dreamer.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Plush Gelert Collar",
            "offenseFireMin": 3,
            "defenseWaterMin": 3,
            "defenseWaterMax": 3,
            "defenseDarkMax": 3,
            "effects": [],
            "offenseLightMin": 3,
            "offenseFireMax": 3,
            "defenseDarkMin": 3,
            "offenseLightMax": 3,
            "id": "Plush Gelert Collar",
            "icon":"https://images.neopets.com/items/bd_gelertcollar.gif",
            "tags": ["L54", "multi-duty", "gelert"]
        },
        {
            "name": "Pyon Stinger Mace",
            "offensePhysicalMin": 3,
            "defenseEarthMax": 5,
            "effects": [],
            "offenseWaterMin": 3,
            "offensePhysicalMax": 3,
            "defenseEarthMin": 5,
            "offenseWaterMax": 3,
            "id": "Pyon Stinger Mace",
            "icon": "https://images.neopets.com/items/bd_mace_pyon.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Rusty Lamppost",
            "defenseDarkMax": 2.714,
            "defensePhysicalMax": 2.714,
            "effects": [],
            "offenseLightMin": 5,
            "defenseDarkMin": 2.714,
            "offenseLightMax": 5,
            "defensePhysicalMin": 2.714,
            "id": "Rusty Lamppost",
            "icon": "https://images.neopets.com/items/hwpp_rustylampost.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Scarab Ring",
            "defenseFireMax": 3,
            "defenseFireMin": 3,
            "defensePhysicalMax": 3,
            "offensePhysicalMin": 2,
            "offenseDarkMax": 2,
            "effects": [],
            "offensePhysicalMax": 2,
            "offenseWaterMin": 2,
            "offenseDarkMin": 2,
            "offenseWaterMax": 2,
            "defensePhysicalMin": 3,
            "id": "Scarab Ring",
            "icon": "https://images.neopets.com/items/bd_ring_scarab.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Seti Hilt Sword",
            "defensePhysicalMax": 3,
            "offensePhysicalMin": 0.3,
            "effects": [],
            "offensePhysicalMax": 3,
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "offenseEarthMax": 3,
            "offenseEarthMin": 3,
            "defensePhysicalMin": 3,
            "id": "Seti Hilt Sword",
            "icon": "https://images.neopets.com/items/bd_seti_sword.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Silver Korbat Amulet",
            "offenseFireMin": 3,
            "defenseLightMax": 3,
            "defenseEarthMax": 3,
            "offenseDarkMax": 3,
            "effects": [],
            "offenseDarkMin": 3,
            "offenseFireMax": 3,
            "defenseEarthMin": 3,
            "defenseLightMin": 3,
            "id": "Silver Korbat Amulet",
            "icon": "https://images.neopets.com/items/bd_korbat_amulet.gif",
            "tags": ["L54", "multi-duty", "korbat"]
        },
        {
            "name": "Sinister Scythe",
            "offenseFireMin": 3,
            "defenseLightMax": 5,
            "offenseDarkMax": 5,
            "effects": [],
            "offenseDarkMin": 5,
            "offenseFireMax": 3,
            "defenseLightMin": 5,
            "id": "Sinister Scythe",
            "icon": "https://images.neopets.com/items/bd_sinister_sycthe.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Snowager Sword",
            "defenseFireMax": 3,
            "offensePhysicalMin": 3,
            "effects": [],
            "offensePhysicalMax": 3,
            "offenseWaterMin": 2,
            "offenseAirMax": 2,
            "offenseAirMin": 2,
            "defenseFireMin": 3,
            "offenseWaterMax": 2,
            "id": "Snowager Sword",
            "icon": "https://images.neopets.com/items/bd_sword_snowager.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Sophies Wooden Spoon",
            "defenseWaterMin": 5,
            "defenseWaterMax": 5,
            "effects": [],
            "offenseEarthMax": 5.6,
            "offenseEarthMin": 5.6,
            "id": "Sophies Wooden Spoon",
            "icon": "https://images.neopets.com/items/bd_sophie_spoon.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Spiked Negg Mace",
            "defenseEarthMax": 5,
            "effects": [],
            "offenseEarthMax": 5,
            "defenseEarthMin": 5,
            "offenseEarthMin": 5,
            "id": "Spiked Negg Mace",
            "icon": "https://images.neopets.com/items/bd_fony15_spiked_neggmace.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Sword of the Dead",
            "defenseLightMax": 5,
            "offenseDarkMax": 3,
            "effects": [],
            "offenseDarkMin": 3,
            "offenseAirMax": 2.6,
            "offenseAirMin": 2.6,
            "offenseLightMax": 5,
            "id": "Sword of the Dead",
            "icon": "https://images.neopets.com/items/bd_haunted_sword.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "The Scimitar of Lyra",
            "offenseFireMin": 3,
            "defensePhysicalMax": 2.66,
            "effects": [],
            "offenseLightMin": 6,
            "offenseFireMax": 3,
            "offenseLightMax": 6,
            "defensePhysicalMin": 2.66,
            "id": "The Scimitar of Lyra",
            "icon": "https://images.neopets.com/items/wea_lyras_scimitar.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Tooth of Terask",
            "defenseDarkMax": 3,
            "effects": [],
            "offenseWaterMin": 3,
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "offenseWaterMax": 3,
            "defenseDarkMin": 3,
            "id": "Tooth of Terask",
            "icon": "https://images.neopets.com/items/bd_nq2_terask_tooth.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Twisted Dark Dagger",
            "defenseFireMax": 3,
            "defenseLightMax": 3,
            "offensePhysicalMin": 0.3,
            "offenseDarkMax": 3,
            "effects": [],
            "offensePhysicalMax": 3,
            "offenseDarkMin": 3,
            "defenseFireMin": 3,
            "offenseEarthMax": 2,
            "offenseEarthMin": 2,
            "defenseLightMin": 3,
            "id": "Twisted Dark Dagger",
            "icon": "https://images.neopets.com/items/bd_dagger_twisteddark.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Ultimate Negg Hammer",
            "defenseLightMax": 3,
            "offensePhysicalMin": 5,
            "effects": [],
            "offensePhysicalMax": 5,
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "offenseLightMax": 3,
            "id": "Ultimate Negg Hammer",
            "icon": "https://images.neopets.com/items/bd_fony14_negg_hammer.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Ultra Supreme Kiko Walker",
            "defenseEarthMax": 3,
            "offensePhysicalMin": 2.65,
            "effects": [],
            "offensePhysicalMax": 2.65,
            "defenseAirMin": 2,
            "offenseLightMin": 2.65,
            "defenseEarthMin": 3,
            "defenseAirMax": 2,
            "offenseLightMax": 2.65,
            "id": "Ultra Supreme Kiko Walker",
            "icon": "https://images.neopets.com/items/bd_kiko_bodysuit.gif",
            "tags": ["L54", "multi-duty", "kiko"]
        },
        {
            "name": "Wand of the Moon",
            "offenseFireMin": 2,
            "defenseDarkMax": 3,
            "effects": [],
            "offenseLightMin": 2,
            "offenseFireMax": 2,
            "offenseEarthMax": 3,
            "offenseEarthMin": 3,
            "defenseDarkMin": 3,
            "offenseLightMax": 2,
            "id": "Wand of the Moon",
            "icon": "https://images.neopets.com/items/bd_desert_sword2.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Zombie Fist on a Stick",
            "defensePhysicalMax": 5,
            "offensePhysicalMin": 3,
            "effects": [],
            "offensePhysicalMax": 3,
            "offenseEarthMax": 3,
            "offenseEarthMin": 3,
            "defensePhysicalMin": 5,
            "id": "Zombie Fist on a Stick",
            "icon": "https://images.neopets.com/items/bd_zombie_fist_stick.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Wand of Lameness",
            "defenseFireMax": 5,
            "effects": [],
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "defenseFireMin": 5,
            "offenseEarthMax": 3,
            "offenseEarthMin": 3,
            "id": "Wand of Lameness",
            "icon": "https://images.neopets.com/items/bd_tyweof2013_brokenupwand.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Grimoire of Thade",
            "defenseDarkMin": 5,
            "defenseDarkMax": 5,
            "offensePhysicalMin": 0.3,
            "offenseDarkMax": 5,
            "effects": [],
            "offensePhysicalMax": 3,
            "offenseDarkMin": 5,
            "id": "Grimoire of Thade",
            "icon": "https://images.neopets.com/items/eliv_thade_book.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Asparagus Dagger",
            "defenseDarkMax": 5,
            "offensePhysicalMin": 0.3,
            "effects": [],
            "offensePhysicalMax": 3,
            "offenseLightMin": 3,
            "offenseEarthMax": 3,
            "offenseEarthMin": 3,
            "offenseLightMax": 3,
            "id": "Asparagus Dagger",
            "icon": "https://images.neopets.com/items/bd_dagger_asparagus.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Hansos Masamune",
            "defensePhysicalMax": 3,
            "offensePhysicalMin": 5,
            "effects": [],
            "offensePhysicalMax": 5,
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "defensePhysicalMin": 3,
            "id": "Hansos Masamune",
            "icon": "https://images.neopets.com/items/2fcf2aa974.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Amulet of the Unblinking Eye",
            "offenseFireMin": 3,
            "defenseLightMax": 2,
            "offenseDarkMax": 3,
            "effects": [],
            "offenseDarkMin": 3,
            "offenseLightMin": 3,
            "offenseFireMax": 3,
            "defenseLightMin": 2,
            "offenseLightMax": 3,
            "defensePhysicalMin": 0,
            "id": "Amulet of the Unblinking Eye",
            "icon": "https://images.neopets.com/items/bd_unblinking_eye_amulet.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Dusty Magic Broom!",
            "defenseLightMax": 5,
            "effects": [],
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "offenseEarthMax": 5,
            "offenseEarthMin": 5,
            "defenseLightMin": 5,
            "id": "Dusty Magic Broom!",
            "icon": "https://images.neopets.com/items/bd_broom.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Glaive of Verdancy",
            "defenseDarkMax": 5,
            "effects": [],
            "offenseAirMax": 3,
            "offenseAirMin": 3,
            "offenseEarthMax": 5,
            "offenseEarthMin": 5,
            "defenseDarkMin": 5,
            "id": "Glaive of Verdancy",
            "icon": "https://images.neopets.com/items/bd_glaiveverd.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Sinister Scythe",
            "offenseFireMin": 3,
            "defenseLightMax": 5,
            "offenseDarkMax": 5,
            "effects": [],
            "offenseDarkMin": 5,
            "offenseFireMax": 3,
            "defenseLightMin": 5,
            "id": "Sinister Scythe",
            "icon": "https://images.neopets.com/items/bd_sinister_sycthe.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Space Faerie Token",
            "offenseFireMin": 3,
            "defenseDarkMax": 5,
            "effects": [],
            "offenseLightMin": 5,
            "offenseFireMax": 3,
            "defenseDarkMin": 5,
            "offenseLightMax": 5,
            "id": "Space Faerie Token",
            "icon": "https://images.neopets.com/items/bd_spacefaerie_token.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Fighting Folder",
            "offenseFireMin": 3,
            "offensePhysicalMin": 0.3,
            "offenseDarkMax": 0,
            "effects": ["Restores 2 HP on use."],
            "offensePhysicalMax": 3,
            "offenseFireMax": 3,
            "offenseEarthMax": 2,
            "offenseEarthMin": 2,
            "id": "Fighting Folder",
            "icon": "https://images.neopets.com/items/bd_folder.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Sunblade Replica",
            "defenseLightMin": 0,
            "defenseDarkMin": 0,
            "defenseEarthMin": 0,
            "defenseAirMin": 0,
            "defensePhysicalMin": 0,
            "defenseLightMax": 2,
            "defenseDarkMax": 2,
            "defensePhysicalMax": 2,
            "defenseEarthMax": 2,
            "defenseAirMax": 2,
            "offensePhysicalMin": 0.3,
            "effects": ["Defends 2 icons of each of Earth, Light, Dark, Air, and Physical when you also deal dark damage."],
            "offensePhysicalMax": 3,
            "offenseLightMin": 3,
            "offenseLightMax": 3,
            "id": "Sunblade Replica",
            "icon": "https://images.neopets.com/items/bd_bfm_sunblade.gif",
            "tags": ["L54", "multi-duty"]
        },
        {
            "name": "Downsize!",
            "effects": ["Reduces all damage received by 50%. Once per battle."],
            "id": "Downsize!",
            "percentageEarthBlocked": 50,
            "percentageLightBlocked": 50,
            "percentageFireBlocked": 50,
            "percentageWaterBlocked": 50,
            "percentageDarkBlocked": 50,
            "percentageAirBlocked": 50,
            "percentagePhysicalBlocked": 50,
            "icon": "https://images.neopets.com/items/bd_downsize.gif",
            "tags": ["L54", "blocker"]
        },
        {
            "name": "Pretty Negg Shield",
            "effects": [
              "Blocks 60% of Earth and Light damage.",
              "Reflects 20% of Earth and Light damage back to the attacker."
            ],
            "percentageEarthBlocked": 60,
            "percentageLightBlocked": 60,
            "percentageEarthReflected": 20,
            "percentageLightReflected": 20,
            "id": "Pretty Negg Shield. Blocks 60% Earth/Light",
            "icon": "https://images.neopets.com/items/wea_fonY21_negg_shield.gif",
            "tags": ["L54", "blocker", "reflector"]
        },
        {
            "name": "Nebula Force Field Generator",
            "defenseLightMax": 3,
            "defenseDarkMax": 3,
            "defensePhysicalMax": 3,
            "effects": [],
            "defenseAirMin": 3,
            "defenseAirMax": 3,
            "defenseDarkMin": 3,
            "defenseLightMin": 3,
            "defensePhysicalMin": 3,
            "id": "Nebula Force Field Generator",
            "icon": "https://images.neopets.com/items/spd_gener_nebforce.gif",
            "tags": ["L54", "defense"]
        },
        {
            "name": "Sophies Magic Hat",
            "defenseFireMax": 3,
            "defenseDarkMax": 3,
            "defensePhysicalMax": 3,
            "defenseEarthMax": 5,
            "effects": [],
            "defenseFireMin": 3,
            "defenseEarthMin": 5,
            "defenseDarkMin": 3,
            "defensePhysicalMin": 3,
            "id": "Sophies Magic Hat",
            "icon": "https://images.neopets.com/items/bd_sophie_hat.gif",
            "tags": ["L54", "defense"]
        },
        {
            "name": "Kiko Skull Pirate Hat",
            "defenseWaterMin": 5,
            "defenseWaterMax": 5,
            "defenseDarkMax": 5,
            "defensePhysicalMax": 4,
            "effects": ["Defends 2 extra physical icons when air is present."],
            "defenseDarkMin": 5,
            "defensePhysicalMin": 5,
            "id": "Kiko Skull Pirate Hat",
            "icon": "https://images.neopets.com/items/clo_ddy15_kikoskuph.gif",
            "tags": ["L54", "defense"]
        },
        {
            "name": "Solar Flare Shield",
            "defenseFireMax": 3,
            "defenseWaterMin": 3,
            "defenseWaterMax": 3,
            "defensePhysicalMax": 3,
            "effects": [],
            "defenseAirMin": 3,
            "defenseFireMin": 3,
            "defenseAirMax": 3,
            "defensePhysicalMin": 3,
            "id": "Solar Flare Shield",
            "icon": "https://images.neopets.com/items/spd_shield_solarflare.gif",
            "tags": ["L54", "defense"]
        },
        {
            "name": "Wanderers Cloak",
            "defenseFireMax": 3,
            "defenseWaterMin": 2,
            "defenseWaterMax": 2,
            "defenseLightMax": 3,
            "defenseEarthMax": 5,
            "effects": ["Defends 3 extra earth icons when your opponent has 325 or more intelligence."],
            "defenseAirMin": 2,
            "defenseFireMin": 3,
            "defenseEarthMin": 2,
            "defenseAirMax": 2,
            "defenseLightMin": 3,
            "id": "Wanderers Cloak",
            "icon": "https://images.neopets.com/items/bva_cloak_wanderers.gif",
            "tags": ["L54", "defense"]
        },
        {
            "name": "Leaf Shield",
            "defenseWaterMin": 5,
            "defenseWaterMax": 5,
            "defensePhysicalMax": 3,
            "defensePhysicalMin": 3,
            "defenseEarthMin": 5,
            "defenseEarthMax": 5,
            "effects": [],
            "id": "Leaf Shield",
            "icon": "https://images.neopets.com/items/earth_leafsheild.gif",
            "tags": ["L54", "defense"]
        },
        {
            "name": "Virtupets X-514 Super Shield",
            "defenseWaterMin": 2,
            "defenseWaterMax": 2,
            "defenseLightMax": 2,
            "defenseDarkMax": 2,
            "defensePhysicalMax": 3,
            "defenseEarthMax": 3,
            "effects": [],
            "defenseEarthMin": 3,
            "defenseDarkMin": 2,
            "defenseLightMin": 2,
            "defensePhysicalMin": 0.3,
            "id": "Virtupets X-514 Super Shield",
            "icon": "https://images.neopets.com/items/bd_space_shield.gif",
            "tags": ["L54", "defense"]
        },
        {
            "name": "Parchment Cloak",
            "defenseLightMax": 2.6,
            "defenseDarkMax": 2.6,
            "defenseEarthMax": 1.75,
            "effects": ["Defends 5 extra air icons when your pet's intelligence is 150 or more."],
            "defenseAirMin": 0,
            "defenseEarthMin": 1.75,
            "defenseAirMax": 5,
            "defenseDarkMin": 2.667,
            "defenseLightMin": 2.667,
            "id": "Parchment Cloak",
            "icon": "https://images.neopets.com/items/bva_parchment_cloak.gif",
            "tags": ["L54", "defense"]
        },
        {
            "name": "Parasol of Unfortunate Demise",
            "defenseWaterMin": 3,
            "defenseWaterMax": 3,
            "defenseEarthMin": 1.4,
            "effects": [
                "Blocks 100% of light"
            ],
            "defenseEarthMax": 5,
            "id": "Parasol of Unfortunate Demise",
            "percentageLightBlocked": 100,
            "icon": "https://images.neopets.com/items/shw_parasol_unfortunate.gif",
            "tags": ["L54", "defense", "blocker"]
        },
        {
            "name": "Kaylas Magic Cloak",
            "defenseWaterMin": 5,
            "defenseWaterMax": 5,
            "defenseLightMax": 5,
            "effects": [],
            "defenseAirMin": 5,
            "defenseAirMax": 5,
            "defenseLightMin": 5,
            "id": "Kaylas Magic Cloak",
            "icon": "https://images.neopets.com/items/bd_kayla_cloak.gif",
            "tags": ["L54", "defense"]
        },
        {
            "name": "Royal Blue Cape",
            "defenseFireMax": 3,
            "defenseLightMax": 3,
            "defenseEarthMax": 3,
            "effects": [],
            "defenseAirMin": 3,
            "defenseFireMin": 3,
            "defenseEarthMin": 3,
            "defenseAirMax": 3,
            "defenseLightMin": 3,
            "id": "Royal Blue Cape",
            "icon": "https://images.neopets.com/items/bva_royalblue_cape.gif",
            "tags": ["L54", "defense"]
        },
        {
            "name": "Full Buzz Armour",
            "defenseDarkMax": 3.27,
            "defensePhysicalMax": 3.27,
            "defenseEarthMax": 3.27,
            "defenseAirMax": 3.27,
            "defenseDarkMin": 3.27,
            "defensePhysicalMin": 3.27,
            "defenseEarthMin": 3.27,
            "defenseAirMin": 3.27,
            "effects": [],
            "id": "Full Buzz Armour",
            "icon": "https://images.neopets.com/items/bd_buzz_fullarmour.gif",
            "tags": ["L54", "defense"]
        },
        {
            "name": "Tower Shield",
            "defenseFireMin": 2,
            "defenseFireMax": 2,
            "defenseAirMin": 2,
            "defenseAirMax": 2,
            "defenseEarthMin": 2,
            "defenseEarthMax": 2,
            "defenseLightMin": 2,
            "defenseLightMax": 2,
            "defenseDarkMin": 2,
            "defenseDarkMax": 2,
            "defensePhysicalMin": 2,
            "defensePhysicalMax": 2,
            "effects": [],
            "id": "Tower Shield",
            "icon": "https://images.neopets.com/items/bd_bfm_tower_shield.gif",
            "tags": ["L54", "defense"]
        },
        {
            "name": "Faerie Shield",
            "defenseFireMin": 2,
            "defenseFireMax": 2,
            "defenseAirMin": 2,
            "defenseAirMax": 2,
            "defenseEarthMin": 2,
            "defenseEarthMax": 2,
            "defenseLightMin": 2,
            "defenseLightMax": 2,
            "defenseDarkMin": 2,
            "defenseDarkMax": 2,
            "defenseWaterMin": 2,
            "defenseWaterMax": 2,
            "effects": [],
            "id": "Faerie Shield",
            "icon": "https://images.neopets.com/items/faerie_shield.gif",
            "tags": ["L54", "defense"]
        }
    ],
    "abilities": [
        {
            "id": "Halitosis",
            "name": "Halitosis",
            "effects": [
                "Deals 2 earth damage on this turn and the next turn. 1 turn cooldown after last damage."
            ],
            "offenseEarthMax": 2,
            "offenseEarthMin": 2,
            "icon": "https://images.neopets.com/bd2/abilities/0010_p1yh839wh5_halitosis/thumb_10.png"
        },
        {
            "id": "Static Cling",
            "name": "Static Cling",
            "effects": [
                "Deals 3 light damage on this turn"
            ],
            "offenseLightMax": 3,
            "offenseLightMin": 3,
            "icon": "https://images.neopets.com/bd2/abilities/0001_h743ty2wez_staticcling/thumb_1.png"
        },
        {
            "id": "Shade",
            "name": "Shade",
            "effects": [
                "Protects 3 icons from 3 different elements for 1 turn, except Physical and Dark. 4 turns cooldown. Note: This ability could protect against glitch darkness but not dark."
            ],
            "icon": "https://images.neopets.com/bd2/abilities/0014_jhuh934z0p_shade/thumb_14.png"
        },
        {
            "id": "Positive Thinking",
            "name": "Positive Thinking",
            "effects": [
                "Restores 5% (Up to 2.7, rounded to 3) of your current HP to your Neopet. Once per battle"
            ],
            "icon": "https://images.neopets.com/bd2/abilities/0017_v342uy79hz_thinkpositive/thumb_17.png"
        }
    ]
};